/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.DaoLaporan;
import dao.DaoMenu;
import dao.DaoPelanggan;
import dao.DaoPembelian;
import dao.Rupiah;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import model.DetailPembelian;
import model.DetailPembelianPK;
import model.Menu;
import model.Pelanggan;
import model.Pembelian;
import model.PembelianPK;
import servis.ServisPembelian;
import tabel.TabelDetailP;
import tabel.TabelPembelian;

/**
 *
 * @author fatiq
 */
public class MenuPembelian extends javax.swing.JPanel {

    /**
     * Creates new form MenuPetugas
     */
    private final TabelPembelian tbl = new TabelPembelian();
    private final TabelDetailP tblP = new TabelDetailP();
    private ServisPembelian servis = new DaoPembelian();
    private Pembelian mb = new Pembelian();
    private Menu mod = new Menu();

    public MenuPembelian() {
        initComponents();
        tblConten.setModel(tbl);
        tblConten1.setModel(tblP);
        int[] tbC = {0, 1, 2,6};
        int[] tbCW = {35, 90, 70, 70};
        int[] tbC1 = {0, 1, 5};
        int[] tbC1W = {35, 70, 70};
        setColWidht(tblConten, tbC, tbCW);
        setColWidht(tblConten1, tbC1, tbC1W);
        resetData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnTambah = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        btnBatal21 = new javax.swing.JButton();
        btnSimpan21 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfNo1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanelCustom1 = new custom.JPanelCustom();
        jLabel7 = new javax.swing.JLabel();
        tfTgl = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();
        jPanelCustom5 = new custom.JPanelCustom();
        jPanelCustom6 = new custom.JPanelCustom();
        jLabel12 = new javax.swing.JLabel();
        tfId21 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        tfNama21 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanelCustom7 = new custom.JPanelCustom();
        jPanelCustom8 = new custom.JPanelCustom();
        jLabel14 = new javax.swing.JLabel();
        tfKode21 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        tfNamaMenu21 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfJml21 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfSubtotal21 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tfHarga = new javax.swing.JTextField();
        tfKet21 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnTambah21 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMn21 = new javax.swing.JTable();
        btnHapus21 = new javax.swing.JButton();
        btnUbah21 = new javax.swing.JButton();
        btnBatal22 = new javax.swing.JButton();
        jPanelCustom9 = new custom.JPanelCustom();
        cbxStatus = new javax.swing.JComboBox<>();
        pnData = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConten = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        tfCari = new javax.swing.JTextField();
        cbxCari = new javax.swing.JComboBox<>();
        pnDetail = new javax.swing.JPanel();
        jPanelCustom2 = new custom.JPanelCustom();
        lbTgl = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        tfNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblConten1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        lbIdPel = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbNamaPel = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbIdPet = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lbNamaPet = new javax.swing.JLabel();
        btnBatal1 = new javax.swing.JButton();
        jPanelCustom4 = new custom.JPanelCustom();
        lbStatus = new javax.swing.JLabel();
        jPanelCustom10 = new custom.JPanelCustom();
        lbTotal = new javax.swing.JLabel();
        btnUbah = new javax.swing.JButton();
        btnLunas = new javax.swing.JButton();
        dateCoser = new com.toedter.calendar.JDateChooser();

        setLayout(new java.awt.CardLayout());

        pnMain.setLayout(new java.awt.CardLayout());

        pnTambah.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator3.setBackground(new java.awt.Color(79, 42, 24));
        jSeparator3.setForeground(new java.awt.Color(79, 42, 24));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(79, 42, 24));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pembelian1.png"))); // NOI18N
        jLabel3.setText("Tambah Pembelian");

        btnBatal21.setBackground(new java.awt.Color(166, 145, 138));
        btnBatal21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBatal21.setForeground(new java.awt.Color(166, 145, 138));
        btnBatal21.setText("BATAL");
        btnBatal21.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBatal21MouseMoved(evt);
            }
        });
        btnBatal21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBatal21MouseExited(evt);
            }
        });
        btnBatal21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatal21ActionPerformed(evt);
            }
        });

        btnSimpan21.setBackground(new java.awt.Color(79, 42, 24));
        btnSimpan21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSimpan21.setForeground(new java.awt.Color(79, 42, 24));
        btnSimpan21.setText("SIMPAN");
        btnSimpan21.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSimpan21MouseMoved(evt);
            }
        });
        btnSimpan21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSimpan21MouseExited(evt);
            }
        });
        btnSimpan21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpan21ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cafe2K.png"))); // NOI18N

        tfNo1.setEditable(false);
        tfNo1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfNo1.setForeground(new java.awt.Color(79, 42, 24));
        tfNo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNo1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(79, 42, 24));
        jLabel6.setText("NO :");

        jPanelCustom1.setBackground(new java.awt.Color(79, 42, 24));
        jPanelCustom1.setKananAtas(20);
        jPanelCustom1.setKananBawah(20);
        jPanelCustom1.setKiriAtas(20);
        jPanelCustom1.setKiriBawah(20);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tanggal");

        tfTgl.setEditable(false);
        tfTgl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfTgl.setForeground(new java.awt.Color(79, 42, 24));
        tfTgl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfTgl.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Total");

        tfTotal.setEditable(false);
        tfTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfTotal.setForeground(new java.awt.Color(79, 42, 24));
        tfTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));

        javax.swing.GroupLayout jPanelCustom1Layout = new javax.swing.GroupLayout(jPanelCustom1);
        jPanelCustom1.setLayout(jPanelCustom1Layout);
        jPanelCustom1Layout.setHorizontalGroup(
            jPanelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfTotal)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelCustom1Layout.setVerticalGroup(
            jPanelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCustom1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tfTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanelCustom5.setBackground(new java.awt.Color(79, 42, 24));
        jPanelCustom5.setKananAtas(20);
        jPanelCustom5.setKananBawah(20);
        jPanelCustom5.setKiriAtas(20);
        jPanelCustom5.setKiriBawah(20);

        jPanelCustom6.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCustom6.setKananAtas(20);
        jPanelCustom6.setKananBawah(20);
        jPanelCustom6.setKiriAtas(20);
        jPanelCustom6.setKiriBawah(20);

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(79, 42, 24));
        jLabel12.setText("ID Pelanggan");

        tfId21.setEditable(false);
        tfId21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfId21.setForeground(new java.awt.Color(79, 42, 24));
        tfId21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfId21.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));

        jButton4.setBackground(new java.awt.Color(166, 145, 138));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Tambah Bahan");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tfNama21.setEditable(false);
        tfNama21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfNama21.setForeground(new java.awt.Color(79, 42, 24));
        tfNama21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNama21.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(79, 42, 24));
        jLabel13.setText("Nama");

        javax.swing.GroupLayout jPanelCustom6Layout = new javax.swing.GroupLayout(jPanelCustom6);
        jPanelCustom6.setLayout(jPanelCustom6Layout);
        jPanelCustom6Layout.setHorizontalGroup(
            jPanelCustom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCustom6Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom6Layout.createSequentialGroup()
                        .addComponent(tfId21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanelCustom6Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelCustom6Layout.createSequentialGroup()
                        .addComponent(tfNama21)
                        .addContainerGap())))
        );
        jPanelCustom6Layout.setVerticalGroup(
            jPanelCustom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCustom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfId21)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNama21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Pelanggan");

        javax.swing.GroupLayout jPanelCustom5Layout = new javax.swing.GroupLayout(jPanelCustom5);
        jPanelCustom5.setLayout(jPanelCustom5Layout);
        jPanelCustom5Layout.setHorizontalGroup(
            jPanelCustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCustom6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCustom5Layout.setVerticalGroup(
            jPanelCustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCustom6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelCustom7.setBackground(new java.awt.Color(79, 42, 24));
        jPanelCustom7.setKananAtas(20);
        jPanelCustom7.setKananBawah(20);
        jPanelCustom7.setKiriAtas(20);
        jPanelCustom7.setKiriBawah(20);

        jPanelCustom8.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCustom8.setKananAtas(20);
        jPanelCustom8.setKananBawah(20);
        jPanelCustom8.setKiriAtas(20);
        jPanelCustom8.setKiriBawah(20);

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(79, 42, 24));
        jLabel14.setText("Kode");

        tfKode21.setEditable(false);
        tfKode21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfKode21.setForeground(new java.awt.Color(79, 42, 24));
        tfKode21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfKode21.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));

        jButton5.setBackground(new java.awt.Color(166, 145, 138));
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Tambah Bahan");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tfNamaMenu21.setEditable(false);
        tfNamaMenu21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfNamaMenu21.setForeground(new java.awt.Color(79, 42, 24));
        tfNamaMenu21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNamaMenu21.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(79, 42, 24));
        jLabel15.setText("Nama");

        tfJml21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfJml21.setForeground(new java.awt.Color(79, 42, 24));
        tfJml21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfJml21.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));
        tfJml21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfJml21KeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(79, 42, 24));
        jLabel17.setText("Jumlah");

        tfSubtotal21.setEditable(false);
        tfSubtotal21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfSubtotal21.setForeground(new java.awt.Color(79, 42, 24));
        tfSubtotal21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSubtotal21.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));

        jLabel19.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(79, 42, 24));
        jLabel19.setText("Subtotal");

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(79, 42, 24));
        jLabel21.setText("Harga");

        tfHarga.setEditable(false);
        tfHarga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfHarga.setForeground(new java.awt.Color(79, 42, 24));
        tfHarga.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfHarga.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));

        tfKet21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfKet21.setForeground(new java.awt.Color(79, 42, 24));
        tfKet21.setText("Tidak Ada");
        tfKet21.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));
        tfKet21.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfKet21FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfKet21FocusLost(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(79, 42, 24));
        jLabel23.setText("Ketrangan");

        javax.swing.GroupLayout jPanelCustom8Layout = new javax.swing.GroupLayout(jPanelCustom8);
        jPanelCustom8.setLayout(jPanelCustom8Layout);
        jPanelCustom8Layout.setHorizontalGroup(
            jPanelCustom8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustom8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCustom8Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom8Layout.createSequentialGroup()
                        .addComponent(tfKode21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom8Layout.createSequentialGroup()
                        .addComponent(tfNamaMenu21)
                        .addContainerGap())
                    .addGroup(jPanelCustom8Layout.createSequentialGroup()
                        .addGroup(jPanelCustom8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfJml21, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCustom8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCustom8Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tfHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanelCustom8Layout.createSequentialGroup()
                        .addGroup(jPanelCustom8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelCustom8Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom8Layout.createSequentialGroup()
                        .addGroup(jPanelCustom8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfKet21, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfSubtotal21))
                        .addContainerGap())))
        );
        jPanelCustom8Layout.setVerticalGroup(
            jPanelCustom8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(4, 4, 4)
                .addGroup(jPanelCustom8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfKode21)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNamaMenu21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCustom8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCustom8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfJml21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfHarga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSubtotal21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfKet21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel24.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Menu");

        btnTambah21.setBackground(new java.awt.Color(166, 145, 138));
        btnTambah21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah21.setForeground(new java.awt.Color(166, 145, 138));
        btnTambah21.setText("TAMBAH MENU");
        btnTambah21.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnTambah21MouseMoved(evt);
            }
        });
        btnTambah21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTambah21MouseExited(evt);
            }
        });
        btnTambah21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCustom7Layout = new javax.swing.GroupLayout(jPanelCustom7);
        jPanelCustom7.setLayout(jPanelCustom7Layout);
        jPanelCustom7Layout.setHorizontalGroup(
            jPanelCustom7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustom7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCustom8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTambah21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCustom7Layout.setVerticalGroup(
            jPanelCustom7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCustom8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTambah21)
                .addContainerGap())
        );

        tblMn21.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama", "Harga", "Jumlah", "Subtotal", "Keterangan"
            }
        ));
        tblMn21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMn21MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblMn21);

        btnHapus21.setBackground(new java.awt.Color(200, 0, 0));
        btnHapus21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus21.setForeground(new java.awt.Color(200, 0, 0));
        btnHapus21.setText("HAPUS MENU");
        btnHapus21.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnHapus21MouseMoved(evt);
            }
        });
        btnHapus21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHapus21MouseExited(evt);
            }
        });
        btnHapus21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapus21ActionPerformed(evt);
            }
        });

        btnUbah21.setBackground(new java.awt.Color(79, 42, 24));
        btnUbah21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUbah21.setForeground(new java.awt.Color(79, 42, 24));
        btnUbah21.setText("UBAH MENU");
        btnUbah21.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnUbah21MouseMoved(evt);
            }
        });
        btnUbah21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUbah21MouseExited(evt);
            }
        });
        btnUbah21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbah21ActionPerformed(evt);
            }
        });

        btnBatal22.setBackground(new java.awt.Color(166, 145, 138));
        btnBatal22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBatal22.setForeground(new java.awt.Color(166, 145, 138));
        btnBatal22.setLabel("BATAL");
        btnBatal22.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBatal22MouseMoved(evt);
            }
        });
        btnBatal22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBatal22MouseExited(evt);
            }
        });
        btnBatal22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatal22ActionPerformed(evt);
            }
        });

        jPanelCustom9.setBackground(new java.awt.Color(166, 145, 138));
        jPanelCustom9.setKananAtas(20);
        jPanelCustom9.setKananBawah(20);
        jPanelCustom9.setKiriAtas(20);
        jPanelCustom9.setKiriBawah(20);

        cbxStatus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbxStatus.setForeground(new java.awt.Color(79, 42, 24));
        cbxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nunggak", "Lunas" }));

        javax.swing.GroupLayout jPanelCustom9Layout = new javax.swing.GroupLayout(jPanelCustom9);
        jPanelCustom9.setLayout(jPanelCustom9Layout);
        jPanelCustom9Layout.setHorizontalGroup(
            jPanelCustom9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCustom9Layout.setVerticalGroup(
            jPanelCustom9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnTambahLayout = new javax.swing.GroupLayout(pnTambah);
        pnTambah.setLayout(pnTambahLayout);
        pnTambahLayout.setHorizontalGroup(
            pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(pnTambahLayout.createSequentialGroup()
                .addGroup(pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTambahLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnTambahLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelCustom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelCustom5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSimpan21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBatal21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelCustom9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelCustom7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnTambahLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(pnTambahLayout.createSequentialGroup()
                                .addComponent(btnUbah21, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBatal22, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus21, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        pnTambahLayout.setVerticalGroup(
            pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTambahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfNo1)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnTambahLayout.createSequentialGroup()
                        .addComponent(jPanelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelCustom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelCustom9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnSimpan21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal21))
                    .addGroup(pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTambahLayout.createSequentialGroup()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnUbah21)
                                .addComponent(btnHapus21)
                                .addComponent(btnBatal22)))
                        .addComponent(jPanelCustom7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        pnMain.add(pnTambah, "card3");

        pnData.setBackground(new java.awt.Color(255, 255, 255));

        tblConten.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblConten.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblContenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblConten);

        btnTambah.setBackground(new java.awt.Color(79, 42, 24));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(79, 42, 24));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tambah1.png"))); // NOI18N
        btnTambah.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnTambahMouseMoved(evt);
            }
        });
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTambahMouseExited(evt);
            }
        });
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(200, 0, 0));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(200, 0, 0));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hapus1.png"))); // NOI18N
        btnHapus.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnHapusMouseMoved(evt);
            }
        });
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHapusMouseExited(evt);
            }
        });
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(0, 0, 200));
        btnBatal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(0, 0, 200));
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/batal1.png"))); // NOI18N
        btnBatal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBatalMouseMoved(evt);
            }
        });
        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBatalMouseExited(evt);
            }
        });
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(79, 42, 24));
        jSeparator1.setForeground(new java.awt.Color(79, 42, 24));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(79, 42, 24));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pembelian1.png"))); // NOI18N
        jLabel1.setText("Data Pembelian");

        btnCari.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cari.png"))); // NOI18N
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        tfCari.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tfCari.setForeground(new java.awt.Color(204, 204, 204));
        tfCari.setText("Cari");
        tfCari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        tfCari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCariFocusLost(evt);
            }
        });

        cbxCari.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cbxCari.setForeground(new java.awt.Color(204, 204, 204));
        cbxCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "TANGGAL", "PETUGAS", "PELANGGAN", "STATUS" }));
        cbxCari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        cbxCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCariActionPerformed(evt);
            }
        });

        pnDetail.setBackground(new java.awt.Color(255, 255, 255));
        pnDetail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 42, 24)));

        jPanelCustom2.setBackground(new java.awt.Color(79, 42, 24));
        jPanelCustom2.setKananAtas(10);
        jPanelCustom2.setKananBawah(10);
        jPanelCustom2.setKiriAtas(10);
        jPanelCustom2.setKiriBawah(10);
        jPanelCustom2.setLayout(new java.awt.BorderLayout());

        lbTgl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbTgl.setForeground(new java.awt.Color(255, 255, 255));
        lbTgl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTgl.setText("Tanggal ");
        jPanelCustom2.add(lbTgl, java.awt.BorderLayout.CENTER);

        jSeparator2.setBackground(new java.awt.Color(79, 42, 24));
        jSeparator2.setForeground(new java.awt.Color(79, 42, 24));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(79, 42, 24));
        jLabel2.setText("Detail Pembelian");

        tfNo.setEditable(false);
        tfNo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfNo.setForeground(new java.awt.Color(79, 42, 24));
        tfNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(79, 42, 24));
        jLabel4.setText("NO :");

        tblConten1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblConten1);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(79, 42, 24));
        jLabel16.setText("ID Pelanggan      :");

        lbIdPel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbIdPel.setForeground(new java.awt.Color(79, 42, 24));
        lbIdPel.setText("Tanggal ");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(79, 42, 24));
        jLabel18.setText("Nama Pelanggan :");

        lbNamaPel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbNamaPel.setForeground(new java.awt.Color(79, 42, 24));
        lbNamaPel.setText("Tanggal ");

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(79, 42, 24));
        jLabel20.setText("ID Pegawai      :");

        lbIdPet.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbIdPet.setForeground(new java.awt.Color(79, 42, 24));
        lbIdPet.setText("Tanggal ");

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(79, 42, 24));
        jLabel22.setText("Nama Pegawai :");

        lbNamaPet.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbNamaPet.setForeground(new java.awt.Color(79, 42, 24));
        lbNamaPet.setText("Tanggal ");

        btnBatal1.setBackground(new java.awt.Color(0, 200, 0));
        btnBatal1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBatal1.setForeground(new java.awt.Color(0, 0, 200));
        btnBatal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/report1.png"))); // NOI18N
        btnBatal1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBatal1MouseMoved(evt);
            }
        });
        btnBatal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBatal1MouseExited(evt);
            }
        });
        btnBatal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatal1ActionPerformed(evt);
            }
        });

        jPanelCustom4.setBackground(new java.awt.Color(166, 145, 138));
        jPanelCustom4.setKananAtas(10);
        jPanelCustom4.setKananBawah(10);
        jPanelCustom4.setKiriAtas(10);
        jPanelCustom4.setKiriBawah(10);
        jPanelCustom4.setLayout(new java.awt.BorderLayout());

        lbStatus.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbStatus.setForeground(new java.awt.Color(79, 42, 24));
        lbStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbStatus.setText("Total");
        jPanelCustom4.add(lbStatus, java.awt.BorderLayout.CENTER);

        jPanelCustom10.setBackground(new java.awt.Color(166, 145, 138));
        jPanelCustom10.setKananAtas(10);
        jPanelCustom10.setKananBawah(10);
        jPanelCustom10.setKiriAtas(10);
        jPanelCustom10.setKiriBawah(10);
        jPanelCustom10.setLayout(new java.awt.CardLayout());

        lbTotal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbTotal.setForeground(new java.awt.Color(79, 42, 24));
        lbTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTotal.setText("Total");
        jPanelCustom10.add(lbTotal, "card2");

        btnUbah.setBackground(new java.awt.Color(79, 42, 24));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(0, 0, 200));
        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit1.png"))); // NOI18N
        btnUbah.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnUbahMouseMoved(evt);
            }
        });
        btnUbah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUbahMouseExited(evt);
            }
        });
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnLunas.setBackground(new java.awt.Color(166, 145, 138));
        btnLunas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLunas.setForeground(new java.awt.Color(166, 145, 138));
        btnLunas.setText("TANDAI LUNAS");
        btnLunas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnLunasMouseMoved(evt);
            }
        });
        btnLunas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLunasMouseExited(evt);
            }
        });
        btnLunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLunasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnDetailLayout = new javax.swing.GroupLayout(pnDetail);
        pnDetail.setLayout(pnDetailLayout);
        pnDetailLayout.setHorizontalGroup(
            pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(pnDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDetailLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelCustom10, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnDetailLayout.createSequentialGroup()
                        .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbNamaPel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(lbIdPel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnDetailLayout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbNamaPet, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnDetailLayout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbIdPet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(79, 79, 79)
                        .addComponent(jPanelCustom4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLunas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal1))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        pnDetailLayout.setVerticalGroup(
            pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfNo)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCustom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCustom10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDetailLayout.createSequentialGroup()
                        .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbIdPet)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbIdPel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbNamaPel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbNamaPet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8))
                    .addComponent(btnBatal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCustom4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLunas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnDataLayout = new javax.swing.GroupLayout(pnData);
        pnData.setLayout(pnDataLayout);
        pnDataLayout.setHorizontalGroup(
            pnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDataLayout.createSequentialGroup()
                        .addGroup(pnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnDataLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1))
                            .addGroup(pnDataLayout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBatal)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 433, Short.MAX_VALUE)
                        .addGroup(pnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbxCari, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnDataLayout.createSequentialGroup()
                                .addComponent(dateCoser, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(pnDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnDataLayout.setVerticalGroup(
            pnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDataLayout.createSequentialGroup()
                        .addGroup(pnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfCari, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                            .addComponent(btnCari, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                            .addComponent(dateCoser, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxCari, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnBatal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHapus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTambah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnMain.add(pnData, "card2");

        add(pnMain, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseExited
        btnTambah.setForeground(new Color(79, 42, 24));
        Icon tambah = new ImageIcon(getClass().getResource("/img/tambah1.png"));
        btnTambah.setIcon(tambah);
    }//GEN-LAST:event_btnTambahMouseExited

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        String sc = tfCari.getText();
        Date sc1 = dateCoser.getDate();
        List list = new ArrayList();
        switch (cbxCari.getSelectedIndex()) {
            case 0:
                list = servis.getByNO(sc);
                break;
            case 1:
                list = servis.getByTanggal(sc1);
                break;
            case 2:
                list = servis.getByPetugas(sc);
                break;
            case 3:
                list = servis.getByPelanggan(sc);
                break;
            case 4:
                list = servis.getByStatus(sc);
                break;
        }
        tbl.setData(list);
    }//GEN-LAST:event_btnCariActionPerformed

    private void tfCariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCariFocusGained
        if (tfCari.getText().equals("Cari") || tfCari.getText().equalsIgnoreCase(""))
            tfCari.setText("");
    }//GEN-LAST:event_tfCariFocusGained

    private void tfCariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCariFocusLost
        if (tfCari.getText().equals("Cari") || tfCari.getText().equalsIgnoreCase(""))
            tfCari.setText("Cari");
    }//GEN-LAST:event_tfCariFocusLost

    private void btnTambahMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseMoved
        btnTambah.setForeground(Color.WHITE);
        Icon tambah = new ImageIcon(getClass().getResource("/img/tambah.png"));
        btnTambah.setIcon(tambah);
    }//GEN-LAST:event_btnTambahMouseMoved

    private void btnHapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseExited
        btnHapus.setForeground(new Color(200, 0, 0));
        btnHapus.setIcon(new ImageIcon(getClass().getResource("/img/hapus1.png")));
    }//GEN-LAST:event_btnHapusMouseExited

    private void btnBatalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseExited
        btnBatal.setForeground(new Color(0, 0, 200));
        btnBatal.setIcon(new ImageIcon(getClass().getResource("/img/batal1.png")));
    }//GEN-LAST:event_btnBatalMouseExited

    private void btnHapusMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseMoved
        btnHapus.setForeground(Color.WHITE);
        btnHapus.setIcon(new ImageIcon(getClass().getResource("/img/hapus.png")));
    }//GEN-LAST:event_btnHapusMouseMoved

    private void btnBatalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseMoved
        btnBatal.setForeground(Color.WHITE);
        btnBatal.setIcon(new ImageIcon(getClass().getResource("/img/batal.png")));
    }//GEN-LAST:event_btnBatalMouseMoved

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        resetData();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        MenuUtama.setAktif(false);
        pnMain.removeAll();
        pnMain.add(pnTambah);
        pnMain.repaint();
        pnMain.revalidate();
        resetTable();
        Date now = new Date();
        SimpleDateFormat nonformat = new SimpleDateFormat("dd-MM-yyyy");
        Pelanggan mod = new DaoPelanggan().getById("P000000001");
        jLabel3.setText("Tambah Pembelian");
        tfNama21.setText(mod.getNama());
        tfId21.setText(mod.getIdPelanggan());
        tfTgl.setText(nonformat.format(now));
        tfNo1.setText(servis.getNomer());
        tfTotal.setText("");
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        String s = (String) tblConten.getValueAt(tblConten.getSelectedRow(), 1);
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/hapus1.png"));
        if (JOptionPane.showConfirmDialog(null, "Menghapus pembelian dengan NO " + s, "Apakah anda yakin", 0, 0, icon) == 0) {
            servis.hapusData(s);
        }
        resetData();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblContenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContenMouseClicked
        btnBatal.setVisible(true);
        btnHapus.setVisible(true);
        pnDetail.setVisible(true);
        mb = servis.getByNo(tblConten.getValueAt(tblConten.getSelectedRow(), 1).toString());
        setDetail();
    }//GEN-LAST:event_tblContenMouseClicked

    private void btnBatal1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatal1MouseMoved
        btnBatal1.setForeground(Color.WHITE);
        btnBatal1.setIcon(new ImageIcon(getClass().getResource("/img/report.png")));
    }//GEN-LAST:event_btnBatal1MouseMoved

    private void btnBatal1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatal1MouseExited
        btnBatal1.setForeground(new Color(0, 200, 0));
        btnBatal1.setIcon(new ImageIcon(getClass().getResource("/img/report1.png")));
    }//GEN-LAST:event_btnBatal1MouseExited

    private void btnBatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatal1ActionPerformed
        String no = tfNo.getText();
        new DaoLaporan().cetakNotaPembelian(servis.getByNo(no));
    }//GEN-LAST:event_btnBatal1ActionPerformed

    private void btnBatal21MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatal21MouseMoved
        btnBatal21.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnBatal21MouseMoved

    private void btnBatal21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatal21MouseExited
        btnBatal21.setForeground(new Color(166, 145, 138));
    }//GEN-LAST:event_btnBatal21MouseExited

    private void btnBatal21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatal21ActionPerformed
        resetData();
    }//GEN-LAST:event_btnBatal21ActionPerformed

    private void btnSimpan21MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpan21MouseMoved
        btnSimpan21.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnSimpan21MouseMoved

    private void btnSimpan21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpan21MouseExited
        btnSimpan21.setForeground(new Color(79, 42, 24));
    }//GEN-LAST:event_btnSimpan21MouseExited

    private void btnSimpan21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpan21ActionPerformed
        if (validPesanan()) {
            Pembelian mod = new Pembelian();
            PembelianPK pk = new PembelianPK();
            pk.setNoPembelian(tfNo1.getText());
            pk.setIdPegawai(MenuUtama.mod.getIdPegawai());
            pk.setIdPelanggan(tfId21.getText());
            mod.setPembelianPK(pk);
            mod.setPegawai(MenuUtama.mod);
            mod.setPelanggan(new DaoPelanggan().getById(tfId21.getText()));
            mod.setTgl(tfTgl.getText());
            mod.setTotal(Rupiah.getBigInt(tfTotal.getText()));
            List<DetailPembelian> list = new ArrayList();
            DefaultTableModel tbl1 = (DefaultTableModel) tblMn21.getModel();
            int index = tbl1.getRowCount() - 1;
            for (int i = 0; i <= index; i++) {
                DetailPembelian p = new DetailPembelian();
                DetailPembelianPK ds = new DetailPembelianPK();
                Menu bn = new DaoMenu().getByKode(tbl1.getValueAt(i, 0).toString());
                ds.setKodeMenu(bn.getKodeMenu());
                ds.setIdPegawai(mod.getPembelianPK().getIdPegawai());
                ds.setIdPelanggan(mod.getPembelianPK().getIdPelanggan());
                ds.setNoPembelian(mod.getPembelianPK().getNoPembelian());
                p.setMenu(bn);
                p.setJumlah(Integer.parseInt(tbl1.getValueAt(i, 3).toString()));
                p.setSubtotal(Rupiah.getBigInt(tbl1.getValueAt(i, 4).toString()));
                p.setDetailPembelianPK(ds);
                p.setPembelian(mod);
                p.setKeterangan(tbl1.getValueAt(i, 5).toString());
                list.add(p);
            }
            mod.setDetailPembelianCollection(list);
            mod.setStatus(cbxStatus.getSelectedItem().toString());
            if (jLabel3.getText().equals("Tambah Pembelian")) {
                servis.tambahData(mod);
            } else {
                servis.ubahData(mod);
            }
            resetTable();
            tfNo.setText(servis.getNomer());
            tfTotal.setText("");
            tbl1.setRowCount(0);
            jLabel3.setText("Tambah Pembelian");
            cbxStatus.setSelectedIndex(0);
            String s = "Pembelian berhasil.\nApakah anda ingin mencetak nota ?";
            ImageIcon icon = new ImageIcon(getClass().getResource("/img/laporan1.png"));
            if (JOptionPane.showConfirmDialog(this, s, "Pemberitahuan", 0, 0, icon) == 0) {
                new DaoLaporan().cetakNotaPembelian(mod);
            }
        }
        jLabel1.requestFocus();
    }//GEN-LAST:event_btnSimpan21ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        PilihPelanggan pn = new PilihPelanggan(null, true);
        pn.setVisible(true);
        try {
            tfId21.setText(pn.mod.getIdPelanggan());
            tfNama21.setText(pn.mod.getNama());
        } catch (NullPointerException e) {
        }
        jLabel1.requestFocus();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        PilihMenu pn = new PilihMenu(null, true);
        pn.setVisible(true);
        try {
            this.mod = pn.mod;
            tfKode21.setText(pn.mod.getKodeMenu());
            tfNamaMenu21.setText(pn.mod.getNama());
            tfHarga.setText(Rupiah.getRp(pn.mod.getHarga()));
        } catch (NullPointerException e) {
        }
        jLabel1.requestFocus();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tfJml21KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfJml21KeyTyped
        char a = evt.getKeyChar();
        if (!Character.isDigit(a)) {
            evt.consume();
        } else {
            String s = tfJml21.getText() + String.copyValueOf(new char[]{a});
            long l = Rupiah.getLong(tfHarga.getText());
            tfSubtotal21.setText(Rupiah.getRp(l * Long.parseLong(s)));
        }
    }//GEN-LAST:event_tfJml21KeyTyped

    private void tfKet21FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfKet21FocusGained
        if (tfKet21.getText().equals("Tidak Ada"))
            tfKet21.setText("");
    }//GEN-LAST:event_tfKet21FocusGained

    private void tfKet21FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfKet21FocusLost
        if (tfKet21.getText().equals(""))
            tfKet21.setText("Tidak Ada");
    }//GEN-LAST:event_tfKet21FocusLost

    private void btnTambah21MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambah21MouseMoved
        btnTambah21.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnTambah21MouseMoved

    private void btnTambah21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambah21MouseExited
        btnTambah21.setForeground(new Color(166, 145, 138));
    }//GEN-LAST:event_btnTambah21MouseExited

    private void btnTambah21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah21ActionPerformed
        if (validMenu()) {
            DefaultTableModel tbl1 = (DefaultTableModel) tblMn21.getModel();
            String kode = tfKode21.getText();
            String nama = tfNamaMenu21.getText();
            int jml = Integer.parseInt(tfJml21.getText());
            long harga = Rupiah.getLong(tfHarga.getText());
            long subtotal = jml * harga;
            String ket = tfKet21.getText();
            int c = -1;
            for (int i = 0; i < tbl1.getRowCount(); i++) {
                if (tbl1.getValueAt(i, 0).toString().equals(kode)) {
                    c = i;
                }
            }
            if (c == -1) {
                if (jml > mod.getStok()) {
                    JOptionPane.showMessageDialog(this, "Stok " + mod.getNama() + " tersisa " + mod.getStok());
                } else {
                    tbl1.addRow(new Object[]{kode, nama, Rupiah.getRp(harga), jml, Rupiah.getRp(subtotal), ket});
                    resetTable();
                }
            } else {
                int nJml = Integer.parseInt(tbl1.getValueAt(c, 3).toString()) + jml;
                long nSubtotal = Rupiah.getLong(tbl1.getValueAt(c, 4).toString()) + subtotal;
                if (btnTambah21.getText().equals("TAMBAH MENU")) {
                    if (nJml > mod.getStok()) {
                        JOptionPane.showMessageDialog(this, "Stok " + mod.getNama() + " tersisa " + mod.getStok());
                    } else {
                        tbl1.setValueAt(nJml, c, 3);
                        tbl1.setValueAt(Rupiah.getRp(nSubtotal), c, 4);
                        tbl1.setValueAt(ket, c, 5);
                        resetTable();
                    }
                } else {
                    if (jml > mod.getStok()) {
                        JOptionPane.showMessageDialog(this, "Stok " + mod.getNama() + " tersisa " + mod.getStok());
                    } else {
                        tbl1.setValueAt(jml, c, 3);
                        tbl1.setValueAt(Rupiah.getRp(subtotal), c, 4);
                        tbl1.setValueAt(ket, c, 5);
                        resetTable();
                    }
                }
            }
            tblMn21.setModel(tbl1);
            setTotal();
        }
        jLabel1.requestFocus();
    }//GEN-LAST:event_btnTambah21ActionPerformed

    private void tblMn21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMn21MouseClicked
        btnHapus21.setVisible(true);
        btnUbah21.setVisible(true);
        btnBatal22.setVisible(true);
    }//GEN-LAST:event_tblMn21MouseClicked

    private void btnHapus21MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapus21MouseMoved
        btnHapus21.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnHapus21MouseMoved

    private void btnHapus21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapus21MouseExited
        btnHapus21.setForeground(new Color(200, 0, 0));
    }//GEN-LAST:event_btnHapus21MouseExited

    private void btnHapus21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapus21ActionPerformed
        DefaultTableModel tbl = (DefaultTableModel) tblMn21.getModel();
        int index = tblMn21.getSelectedRow();
        tbl.removeRow(index);
        tblMn21.setModel(tbl);
        jLabel1.requestFocus();
        resetTable();
    }//GEN-LAST:event_btnHapus21ActionPerformed

    private void btnUbah21MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbah21MouseMoved
        btnUbah21.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnUbah21MouseMoved

    private void btnUbah21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbah21MouseExited
        btnUbah21.setForeground(new Color(79, 42, 24));
    }//GEN-LAST:event_btnUbah21MouseExited

    private void btnUbah21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbah21ActionPerformed
        this.mod = new DaoMenu().getByKode(tblMn21.getValueAt(tblMn21.getSelectedRow(), 0).toString());
        tfKode21.setText(mod.getKodeMenu());
        tfNamaMenu21.setText(mod.getNama());
        tfHarga.setText(mod.getRpHarga());
        tfJml21.setText(tblMn21.getValueAt(tblMn21.getSelectedRow(), 3).toString());
        tfSubtotal21.setText(tblMn21.getValueAt(tblMn21.getSelectedRow(), 4).toString());
        tfKet21.setText(tblMn21.getValueAt(tblMn21.getSelectedRow(), 5).toString());
        btnTambah21.setText("PERBARUI MENU");
    }//GEN-LAST:event_btnUbah21ActionPerformed

    private void btnBatal22MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatal22MouseMoved
        btnBatal22.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnBatal22MouseMoved

    private void btnBatal22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatal22MouseExited
        btnBatal22.setForeground(new Color(166, 145, 138));
    }//GEN-LAST:event_btnBatal22MouseExited

    private void btnBatal22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatal22ActionPerformed
        resetTable();
    }//GEN-LAST:event_btnBatal22ActionPerformed

    private void cbxCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCariActionPerformed
        if (cbxCari.getSelectedIndex() == 1) {
            tfCari.setVisible(false);
            dateCoser.setVisible(true);
        } else {
            dateCoser.setVisible(false);
            tfCari.setVisible(true);
        }
        tfCari.setText("Cari");
    }//GEN-LAST:event_cbxCariActionPerformed

    private void btnUbahMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahMouseMoved
        btnUbah.setForeground(new Color(0, 200, 0));
        btnUbah.setIcon(new ImageIcon(getClass().getResource("/img/edit.png")));
    }//GEN-LAST:event_btnUbahMouseMoved

    private void btnUbahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahMouseExited
        btnUbah.setForeground(new Color(79, 42, 24));
        btnUbah.setIcon(new ImageIcon(getClass().getResource("/img/edit1.png")));
    }//GEN-LAST:event_btnUbahMouseExited

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        MenuUtama.setAktif(false);
        pnMain.removeAll();
        pnMain.add(pnTambah);
        pnMain.repaint();
        pnMain.revalidate();
        resetTable();
        Date now = new Date();
        SimpleDateFormat nonformat = new SimpleDateFormat("dd-MM-yyyy");
        Pelanggan mod = mb.getPelanggan();
        jLabel3.setText("Perbarui Pembelian");
        tfNama21.setText(mod.getNama());
        tfId21.setText(mod.getIdPelanggan());
        tfTgl.setText(nonformat.format(now));
        tfNo1.setText(mb.getPembelianPK().getNoPembelian());
        tfTotal.setText(mb.getRpTotal());
        DefaultTableModel tb = (DefaultTableModel) tblMn21.getModel();
        tb.setRowCount(0);
        for(DetailPembelian dp : mb.getDetailPembelianCollection()){
            tb.addRow(new Object[]{
                dp.getMenu().getKodeMenu(),
                dp.getMenu().getNama(),
                dp.getMenu().getRpHarga(),
                dp.getJumlah(),
                dp.getRpSubtotal(),
                dp.getKeterangan()
            });
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnLunasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLunasMouseMoved
        btnLunas.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnLunasMouseMoved

    private void btnLunasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLunasMouseExited
        btnLunas.setForeground(new Color(166,145,138));
    }//GEN-LAST:event_btnLunasMouseExited

    private void btnLunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLunasActionPerformed
        mb.setStatus("Lunas");
        servis.ubahData(mb);
        tbl.setData(servis.ambilData());
        setDetail();
        jLabel1.requestFocus();
    }//GEN-LAST:event_btnLunasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBatal1;
    private javax.swing.JButton btnBatal21;
    private javax.swing.JButton btnBatal22;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHapus21;
    private javax.swing.JButton btnLunas;
    private javax.swing.JButton btnSimpan21;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTambah21;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton btnUbah21;
    private javax.swing.JComboBox<String> cbxCari;
    private javax.swing.JComboBox<String> cbxStatus;
    private com.toedter.calendar.JDateChooser dateCoser;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private custom.JPanelCustom jPanelCustom1;
    private custom.JPanelCustom jPanelCustom10;
    private custom.JPanelCustom jPanelCustom2;
    private custom.JPanelCustom jPanelCustom4;
    private custom.JPanelCustom jPanelCustom5;
    private custom.JPanelCustom jPanelCustom6;
    private custom.JPanelCustom jPanelCustom7;
    private custom.JPanelCustom jPanelCustom8;
    private custom.JPanelCustom jPanelCustom9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbIdPel;
    private javax.swing.JLabel lbIdPet;
    private javax.swing.JLabel lbNamaPel;
    private javax.swing.JLabel lbNamaPet;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbTgl;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JPanel pnData;
    private javax.swing.JPanel pnDetail;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnTambah;
    private javax.swing.JTable tblConten;
    private javax.swing.JTable tblConten1;
    private javax.swing.JTable tblMn21;
    private javax.swing.JTextField tfCari;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfId21;
    private javax.swing.JTextField tfJml21;
    private javax.swing.JTextField tfKet21;
    private javax.swing.JTextField tfKode21;
    private javax.swing.JTextField tfNama21;
    private javax.swing.JTextField tfNamaMenu21;
    private javax.swing.JTextField tfNo;
    private javax.swing.JTextField tfNo1;
    private javax.swing.JTextField tfSubtotal21;
    private javax.swing.JTextField tfTgl;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables

    private void resetData() {
        pnMain.removeAll();
        pnMain.add(pnData);
        pnMain.repaint();
        pnMain.revalidate();
        tbl.setData(servis.ambilData());
        btnBatal.setVisible(false);
        btnHapus.setVisible(false);
        pnDetail.setVisible(false);
        btnTambah.setVisible(true);
        dateCoser.setVisible(false);
        MenuUtama.setAktif(true);
        btnTambah.setForeground(new Color(79, 42, 24));
        Icon tambah = new ImageIcon(getClass().getResource("/img/tambah1.png"));
        btnTambah.setIcon(tambah);
        jLabel1.requestFocus();
    }

    private void setColWidht(JTable tb, int[] noCol, int[] noColW) {
        TableColumnModel tblModel = tb.getColumnModel();
        for (int i = 0; i < noCol.length; i++) {
            tblModel.getColumn(noCol[i]).setPreferredWidth(noColW[i]);
            tblModel.getColumn(noCol[i]).setMaxWidth(noColW[i]);
            tblModel.getColumn(noCol[i]).setMinWidth(noColW[i]);
        }
    }

    void resetTable() {
        btnHapus21.setVisible(false);
        btnUbah21.setVisible(false);
        btnBatal22.setVisible(false);
        tblMn21.clearSelection();
        btnTambah21.setText("TAMBAH MENU");

        tfKode21.setText("");
        tfNamaMenu21.setText("");
        tfJml21.setText("");
        tfHarga.setText("0");
        tfSubtotal21.setText("0");
        tfKet21.setText("Tidak Ada");
    }

    private void setTotal() {
        DefaultTableModel tbl = (DefaultTableModel) tblMn21.getModel();
        long i = 0;
        for (int a = 0; a < tbl.getRowCount(); a++) {
            i = i + Rupiah.getLong(tbl.getValueAt(a, 4).toString());
        }
        tfTotal.setText(Rupiah.getRp(i));
    }

    private boolean validMenu() {
        boolean valid = true;
        if (tfKode21.getText().equals("")) {
            valid = false;
            JOptionPane.showMessageDialog(this, "Pilih Menu terlebih dahulu");
        } else if (tfJml21.getText().equals("") || tfJml21.getText().equals("0")) {
            valid = false;
            JOptionPane.showMessageDialog(this, "Masukkan jumlah pesanan terlebih dahulu");
        }
        return valid;
    }

    private boolean validPesanan() {
        boolean valid = true;
        if (tfId21.getText().equals("")) {
            valid = false;
            JOptionPane.showMessageDialog(this, "Pilih Pelangan terlebih dahulu");
        } else if (tblMn21.getRowCount() == 0) {
            valid = false;
            JOptionPane.showMessageDialog(this, "Pilih Menu terlebih dahulu");
        }
        return valid;
    }

    private void setDetail() {
        tfNo.setText(mb.getPembelianPK().getNoPembelian());
        lbTgl.setText(mb.getTgl());
        lbTotal.setText(Rupiah.getRp(mb.getTotal()));
        lbIdPel.setText(mb.getPelanggan().getIdPelanggan());
        lbNamaPel.setText(mb.getPelanggan().getNama());
        lbIdPet.setText(mb.getPegawai().getIdPegawai());
        lbNamaPet.setText(mb.getPegawai().getNama());
        lbStatus.setText(mb.getStatus());
        tblP.setData(mb);
        if (mb.getStatus().equals("Lunas")) {
            btnLunas.setVisible(false);
        } else {
            btnLunas.setVisible(true);
        }
    }
}
