/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import custom.MenuCustom;
import dao.DaoPetugas;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Pegawai;
import servis.ServisPetugas;

/**
 *
 * @author fatiq
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public static boolean aktif = true;
    public static Pegawai mod = new Pegawai();
    private ServisPetugas servis = new DaoPetugas();

    public MenuUtama() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.mod = servis.getById("PT001");
        setEvent();
        btnDasbor.tekan();
    }

    public MenuUtama(Pegawai mod) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.mod = mod;
        setEvent();
        if (!mod.getLevel().equals("Admin")) {
            setLevel();
        }
        btnDasbor.tekan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMenu = new custom.MenuCustom();
        btnDasbor = new custom.MenuCustom();
        btnBahan = new custom.MenuCustom();
        btnPembelian = new custom.MenuCustom();
        btnSupply = new custom.MenuCustom();
        btnSupplier = new custom.MenuCustom();
        btnPelanggan = new custom.MenuCustom();
        btnPetugas = new custom.MenuCustom();
        btnLaporan = new custom.MenuCustom();
        btnMemasak = new custom.MenuCustom();
        pp = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        lv = new javax.swing.JLabel();
        jPanelGradient1 = new custom.JPanelGradient();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cafe2K");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/iconCafe2K.png")).getImage());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnMenu.setaBacground3(new java.awt.Color(166, 145, 138));
        btnMenu.setaIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        btnMenu.setaSelect(new java.awt.Color(79, 42, 24));

        btnDasbor.setaBacground3(new java.awt.Color(166, 145, 138));
        btnDasbor.setaIcon(new javax.swing.ImageIcon(getClass().getResource("/img/monitor.png"))); // NOI18N
        btnDasbor.setaLebel("Dasbord");
        btnDasbor.setaSelect(new java.awt.Color(79, 42, 24));

        btnBahan.setaBacground3(new java.awt.Color(166, 145, 138));
        btnBahan.setaIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bahan.png"))); // NOI18N
        btnBahan.setaLebel("Bahan");
        btnBahan.setaSelect(new java.awt.Color(79, 42, 24));

        btnPembelian.setaBacground3(new java.awt.Color(166, 145, 138));
        btnPembelian.setaIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pembelian.png"))); // NOI18N
        btnPembelian.setaLebel("Pembelian");
        btnPembelian.setaSelect(new java.awt.Color(79, 42, 24));

        btnSupply.setaBacground3(new java.awt.Color(166, 145, 138));
        btnSupply.setaIcon(new javax.swing.ImageIcon(getClass().getResource("/img/supply.png"))); // NOI18N
        btnSupply.setaLebel("Supply");
        btnSupply.setaSelect(new java.awt.Color(79, 42, 24));

        btnSupplier.setaBacground3(new java.awt.Color(166, 145, 138));
        btnSupplier.setaIcon(new javax.swing.ImageIcon(getClass().getResource("/img/supplier.png"))); // NOI18N
        btnSupplier.setaLebel("Supplier");
        btnSupplier.setaSelect(new java.awt.Color(79, 42, 24));

        btnPelanggan.setaBacground3(new java.awt.Color(166, 145, 138));
        btnPelanggan.setaIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        btnPelanggan.setaLebel("Pelanggan");
        btnPelanggan.setaSelect(new java.awt.Color(79, 42, 24));

        btnPetugas.setaBacground3(new java.awt.Color(166, 145, 138));
        btnPetugas.setaIcon(new javax.swing.ImageIcon(getClass().getResource("/img/petugas.png"))); // NOI18N
        btnPetugas.setaLebel("Petugas");
        btnPetugas.setaSelect(new java.awt.Color(79, 42, 24));

        btnLaporan.setaBacground3(new java.awt.Color(166, 145, 138));
        btnLaporan.setaIcon(new javax.swing.ImageIcon(getClass().getResource("/img/laporan.png"))); // NOI18N
        btnLaporan.setaLebel("Laporan");
        btnLaporan.setaSelect(new java.awt.Color(79, 42, 24));

        btnMemasak.setaBacground3(new java.awt.Color(166, 145, 138));
        btnMemasak.setaIcon(new javax.swing.ImageIcon(getClass().getResource("/img/masak.png"))); // NOI18N
        btnMemasak.setaLebel("Memasak");
        btnMemasak.setaSelect(new java.awt.Color(79, 42, 24));

        pp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/foto.png"))); // NOI18N
        pp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ppMouseClicked(evt);
            }
        });

        username.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        username.setForeground(new java.awt.Color(79, 42, 24));
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.setText("Username");
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameMouseClicked(evt);
            }
        });

        lv.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lv.setForeground(new java.awt.Color(79, 42, 24));
        lv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lv.setText("Level");
        lv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lvMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDasbor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBahan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPembelian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSupply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPetugas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMemasak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lv)
                .addGap(18, 18, 18)
                .addComponent(btnDasbor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSupply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMemasak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanelGradient1.setCEnd(new java.awt.Color(79, 42, 24));
        jPanelGradient1.setCStart(new java.awt.Color(166, 145, 138));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogoCafe2K.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelGradient1Layout = new javax.swing.GroupLayout(jPanelGradient1);
        jPanelGradient1.setLayout(jPanelGradient1Layout);
        jPanelGradient1Layout.setHorizontalGroup(
            jPanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGradient1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 945, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(16, 16, 16))
        );
        jPanelGradient1Layout.setVerticalGroup(
            jPanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGradient1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGradient1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanelGradient1, java.awt.BorderLayout.PAGE_START);

        pnMain.setBackground(new java.awt.Color(255, 255, 255));
        pnMain.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Icon icon = new ImageIcon(getClass().getResource("/img/logout1.png"));
        if (JOptionPane.showConfirmDialog(null, "Logout", "Apakah anda yakin", 0, 0, icon) == 0) {
            FormLogin menu = new FormLogin();
            menu.setVisible(true);
            menu.revalidate();
            dispose();
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void ppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppMouseClicked
        profil();
    }//GEN-LAST:event_ppMouseClicked

    private void usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseClicked
        profil();
    }//GEN-LAST:event_usernameMouseClicked

    private void lvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lvMouseClicked
        profil();
    }//GEN-LAST:event_lvMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private custom.MenuCustom btnBahan;
    private custom.MenuCustom btnDasbor;
    private custom.MenuCustom btnLaporan;
    private custom.MenuCustom btnMemasak;
    private custom.MenuCustom btnMenu;
    private custom.MenuCustom btnPelanggan;
    private custom.MenuCustom btnPembelian;
    private custom.MenuCustom btnPetugas;
    private custom.MenuCustom btnSupplier;
    private custom.MenuCustom btnSupply;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private custom.JPanelGradient jPanelGradient1;
    private javax.swing.JLabel lv;
    private javax.swing.JPanel pnMain;
    private javax.swing.JLabel pp;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables

    public static void setAktif(boolean bol) {
        MenuUtama.aktif = bol;
        MenuCustom.setAktif(bol);
    }

    private void setEvent() {
        btnDasbor.setAct(null);
        btnMenu.setAct(null);
        btnBahan.setAct(null);
        btnPembelian.setAct(null);
        btnSupply.setAct(null);
        btnSupplier.setAct(null);
        btnPelanggan.setAct(null);
        btnPetugas.setAct(null);
        btnMemasak.setAct(null);
        btnLaporan.setAct(null);
        
        btnDasbor.setAct(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnMenu.reset();
                btnBahan.reset();
                btnPembelian.reset();
                btnSupply.reset();
                btnSupplier.reset();
                btnPelanggan.reset();
                btnPetugas.reset();
                btnMemasak.reset();
                btnLaporan.reset();

                pnMain.removeAll();
                pnMain.add(new MenuDasbor());
                pnMain.repaint();
                pnMain.revalidate();
            }
        });
        btnMenu.setAct(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnDasbor.reset();
                btnBahan.reset();
                btnPembelian.reset();
                btnSupply.reset();
                btnSupplier.reset();
                btnPelanggan.reset();
                btnPetugas.reset();
                btnMemasak.reset();
                btnLaporan.reset();

                pnMain.removeAll();
                pnMain.add(new MenuMenu());
                pnMain.repaint();
                pnMain.revalidate();
            }
        });
        btnBahan.setAct(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnDasbor.reset();
                btnMenu.reset();
                btnPembelian.reset();
                btnSupply.reset();
                btnSupplier.reset();
                btnPelanggan.reset();
                btnPetugas.reset();
                btnMemasak.reset();
                btnLaporan.reset();

                pnMain.removeAll();
                pnMain.add(new MenuBahan());
                pnMain.repaint();
                pnMain.revalidate();
            }
        });
        btnPembelian.setAct(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnDasbor.reset();
                btnMenu.reset();
                btnBahan.reset();
                btnSupply.reset();
                btnSupplier.reset();
                btnPelanggan.reset();
                btnPetugas.reset();
                btnMemasak.reset();
                btnLaporan.reset();

                pnMain.removeAll();
                pnMain.add(new MenuPembelian());
                pnMain.repaint();
                pnMain.revalidate();
            }
        });
        btnSupply.setAct(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnDasbor.reset();
                btnMenu.reset();
                btnBahan.reset();
                btnPembelian.reset();
                btnSupplier.reset();
                btnPelanggan.reset();
                btnPetugas.reset();
                btnMemasak.reset();
                btnLaporan.reset();

                pnMain.removeAll();
                pnMain.add(new MenuSupply());
                pnMain.repaint();
                pnMain.revalidate();
            }
        });
        btnSupplier.setAct(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnDasbor.reset();
                btnMenu.reset();
                btnBahan.reset();
                btnPembelian.reset();
                btnSupply.reset();
                btnPelanggan.reset();
                btnPetugas.reset();
                btnMemasak.reset();
                btnLaporan.reset();

                pnMain.removeAll();
                pnMain.add(new MenuSupplier());
                pnMain.repaint();
                pnMain.revalidate();
            }
        });
        btnPelanggan.setAct(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnDasbor.reset();
                btnMenu.reset();
                btnBahan.reset();
                btnPembelian.reset();
                btnSupply.reset();
                btnSupplier.reset();
                btnPetugas.reset();
                btnMemasak.reset();
                btnLaporan.reset();

                pnMain.removeAll();
                pnMain.add(new MenuPelanggan());
                pnMain.repaint();
                pnMain.revalidate();
            }
        });
        btnPetugas.setAct(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnDasbor.reset();
                btnMenu.reset();
                btnBahan.reset();
                btnPembelian.reset();
                btnSupply.reset();
                btnSupplier.reset();
                btnPelanggan.reset();
                btnMemasak.reset();
                btnLaporan.reset();

                pnMain.removeAll();
                pnMain.add(new MenuPetugas());
                pnMain.repaint();
                pnMain.revalidate();
            }
        });
        btnMemasak.setAct(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnDasbor.reset();
                btnMenu.reset();
                btnBahan.reset();
                btnPembelian.reset();
                btnSupply.reset();
                btnSupplier.reset();
                btnPelanggan.reset();
                btnPetugas.reset();
                btnLaporan.reset();

                pnMain.removeAll();
                pnMain.add(new MenuMasak());
                pnMain.repaint();
                pnMain.revalidate();
            }
        });
        btnLaporan.setAct(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnDasbor.reset();
                btnMenu.reset();
                btnBahan.reset();
                btnPembelian.reset();
                btnSupply.reset();
                btnPetugas.reset();
                btnSupplier.reset();
                btnPelanggan.reset();
                btnMemasak.reset();

                pnMain.removeAll();
//                pn_main.add(new MenuPetugas(pn_main));
                pnMain.repaint();
                pnMain.revalidate();
            }
        });

        username.setText(mod.getUsername());
        lv.setText("Level : " + mod.getLevel());
        if (mod.getFoto() != null) {
            byte[] img = mod.getFoto();
            ImageIcon imgIcon = new ImageIcon(img);
            double lbW = pp.getWidth();
            double lbH = pp.getHeight();
            double imgW = imgIcon.getIconWidth();
            double imgH = imgIcon.getIconHeight();
            double scaleX = (double) lbW / (double) imgW;
            double scaleY = (double) lbH / (double) imgH;
            double scale = Math.min(scaleX, scaleY);
            Image scaleImg = imgIcon.getImage().getScaledInstance((int) (scale * imgW), (int) (scale * imgH), Image.SCALE_SMOOTH);
            pp.setIcon(new ImageIcon(scaleImg));
        }
    }

    private void setLevel() {
        switch (mod.getLevel()) {
            case "Kasir":
                btnBahan.setVisible(false);
                btnSupply.setVisible(false);
                btnSupplier.setVisible(false);
                btnMemasak.setVisible(false);
                break;
            case "Koki":
                btnPembelian.setVisible(false);
                btnSupply.setVisible(false);
                btnSupplier.setVisible(false);
                btnPelanggan.setVisible(false);
                break;
            case "Gudang":
                btnMenu.setVisible(false);
                btnPembelian.setVisible(false);
                btnPelanggan.setVisible(false);
                btnMemasak.setVisible(false);
                break;
        }
        btnPetugas.setVisible(false);
        btnLaporan.setVisible(false);
    }

    private void profil() {
        btnDasbor.reset();
        btnMenu.reset();
        btnBahan.reset();
        btnPembelian.reset();
        btnSupply.reset();
        btnPetugas.reset();
        btnSupplier.reset();
        btnPelanggan.reset();
        btnMemasak.reset();
        btnLaporan.reset();

        pnMain.removeAll();
        pnMain.add(new MenuProfil());
        pnMain.repaint();
        pnMain.revalidate();
    }
}
