/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.DaoBahan;
import dao.DaoLaporan;
import dao.DaoSupplier;
import dao.DaoSupply;
import dao.Rupiah;
import java.awt.Color;
import java.math.BigInteger;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import model.DetailSupply;
import model.DetailSupplyPK;
import model.Supplier;
import model.Supply;
import model.SupplyPK;
import servis.ServisSupply;
import tabel.TabelDetailS;
import tabel.TabelSupply;

/**
 *
 * @author fatiq
 */
public class MenuSupply extends javax.swing.JPanel {

    /**
     * Creates new form MenuPetugas
     */
    private final TabelSupply tbl = new TabelSupply();
    private final TabelDetailS tblP = new TabelDetailS();
    private ServisSupply servis = new DaoSupply();

    public MenuSupply() {
        initComponents();
        resetData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnData = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConten = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        tfCari = new javax.swing.JTextField();
        cbxCari = new javax.swing.JComboBox<>();
        pnDetail = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        tfNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblConten1 = new javax.swing.JTable();
        btnBatal1 = new javax.swing.JButton();
        jPanelCustom6 = new custom.JPanelCustom();
        lbTgl = new javax.swing.JLabel();
        jPanelCustom7 = new custom.JPanelCustom();
        lbTotal = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbIdPet = new javax.swing.JLabel();
        lbNamaPet = new javax.swing.JLabel();
        lbIdPel = new javax.swing.JLabel();
        lbNamaPel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        dateCoser = new com.toedter.calendar.JDateChooser();
        pnTambah = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        btnBatal2 = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfNo1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanelCustom1 = new custom.JPanelCustom();
        jLabel7 = new javax.swing.JLabel();
        tfTgl = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();
        jPanelCustom2 = new custom.JPanelCustom();
        jPanelCustom4 = new custom.JPanelCustom();
        jLabel13 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        tfNama = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanelCustom3 = new custom.JPanelCustom();
        jPanelCustom5 = new custom.JPanelCustom();
        jLabel17 = new javax.swing.JLabel();
        tfKode = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        tfNamaMenu = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tfJml = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tfSubtotal = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tfHarga = new javax.swing.JTextField();
        tfKet = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        btnTambah1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMn = new javax.swing.JTable();
        btnHapus1 = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnBatal3 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        pnMain.setLayout(new java.awt.CardLayout());

        pnData.setBackground(new java.awt.Color(255, 255, 255));

        tblConten.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblConten.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblContenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblConten);

        btnTambah.setBackground(new java.awt.Color(79, 42, 24));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(79, 42, 24));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tambah1.png"))); // NOI18N
        btnTambah.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnTambahMouseMoved(evt);
            }
        });
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTambahMouseExited(evt);
            }
        });
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(200, 0, 0));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(200, 0, 0));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hapus1.png"))); // NOI18N
        btnHapus.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnHapusMouseMoved(evt);
            }
        });
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHapusMouseExited(evt);
            }
        });
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(0, 0, 200));
        btnBatal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(0, 0, 200));
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/batal1.png"))); // NOI18N
        btnBatal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBatalMouseMoved(evt);
            }
        });
        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBatalMouseExited(evt);
            }
        });
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(79, 42, 24));
        jSeparator1.setForeground(new java.awt.Color(79, 42, 24));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(79, 42, 24));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/supply1.png"))); // NOI18N
        jLabel1.setText("Data Supply");

        btnCari.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cari.png"))); // NOI18N
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        tfCari.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tfCari.setForeground(new java.awt.Color(204, 204, 204));
        tfCari.setText("Cari");
        tfCari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        tfCari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCariFocusLost(evt);
            }
        });

        cbxCari.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cbxCari.setForeground(new java.awt.Color(204, 204, 204));
        cbxCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "TANGGAL", "PETUGAS", "PELANGGAN" }));
        cbxCari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        cbxCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCariActionPerformed(evt);
            }
        });

        pnDetail.setBackground(new java.awt.Color(255, 255, 255));
        pnDetail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 42, 24)));

        jSeparator2.setBackground(new java.awt.Color(79, 42, 24));
        jSeparator2.setForeground(new java.awt.Color(79, 42, 24));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(79, 42, 24));
        jLabel2.setText("Detail Supply");

        tfNo.setEditable(false);
        tfNo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfNo.setForeground(new java.awt.Color(79, 42, 24));
        tfNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(79, 42, 24));
        jLabel4.setText("NO :");

        tblConten1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblConten1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblConten1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblConten1);

        btnBatal1.setBackground(new java.awt.Color(0, 200, 0));
        btnBatal1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBatal1.setForeground(new java.awt.Color(0, 0, 200));
        btnBatal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/report1.png"))); // NOI18N
        btnBatal1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBatal1MouseMoved(evt);
            }
        });
        btnBatal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBatal1MouseExited(evt);
            }
        });
        btnBatal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatal1ActionPerformed(evt);
            }
        });

        jPanelCustom6.setBackground(new java.awt.Color(79, 42, 24));
        jPanelCustom6.setKananAtas(10);
        jPanelCustom6.setKananBawah(10);
        jPanelCustom6.setKiriAtas(10);
        jPanelCustom6.setKiriBawah(10);
        jPanelCustom6.setLayout(new java.awt.BorderLayout());

        lbTgl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbTgl.setForeground(new java.awt.Color(255, 255, 255));
        lbTgl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTgl.setText("Tanggal ");
        jPanelCustom6.add(lbTgl, java.awt.BorderLayout.CENTER);

        jPanelCustom7.setBackground(new java.awt.Color(166, 145, 138));
        jPanelCustom7.setKananAtas(10);
        jPanelCustom7.setKananBawah(10);
        jPanelCustom7.setKiriAtas(10);
        jPanelCustom7.setKiriBawah(10);
        jPanelCustom7.setLayout(new java.awt.CardLayout());

        lbTotal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbTotal.setForeground(new java.awt.Color(79, 42, 24));
        lbTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTotal.setText("Total");
        jPanelCustom7.add(lbTotal, "card2");

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(79, 42, 24));
        jLabel22.setText("Nama Pegawai :");

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(79, 42, 24));
        jLabel20.setText("ID Pegawai      :");

        lbIdPet.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbIdPet.setForeground(new java.awt.Color(79, 42, 24));
        lbIdPet.setText("Tanggal ");

        lbNamaPet.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbNamaPet.setForeground(new java.awt.Color(79, 42, 24));
        lbNamaPet.setText("Tanggal ");

        lbIdPel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbIdPel.setForeground(new java.awt.Color(79, 42, 24));
        lbIdPel.setText("Tanggal ");

        lbNamaPel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbNamaPel.setForeground(new java.awt.Color(79, 42, 24));
        lbNamaPel.setText("Tanggal ");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(79, 42, 24));
        jLabel16.setText("ID Pelanggan      :");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(79, 42, 24));
        jLabel18.setText("Nama Pelanggan :");

        javax.swing.GroupLayout pnDetailLayout = new javax.swing.GroupLayout(pnDetail);
        pnDetail.setLayout(pnDetailLayout);
        pnDetailLayout.setHorizontalGroup(
            pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(pnDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDetailLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelCustom6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelCustom7, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDetailLayout.createSequentialGroup()
                        .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbNamaPel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbIdPel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnDetailLayout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbNamaPet, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnDetailLayout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbIdPet, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBatal1)))
                .addContainerGap())
        );
        pnDetailLayout.setVerticalGroup(
            pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfNo)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2)
                    .addComponent(jPanelCustom6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCustom7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDetailLayout.createSequentialGroup()
                        .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbIdPet)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbIdPel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbNamaPel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbNamaPet))
                            .addComponent(jLabel18)))
                    .addComponent(btnBatal1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnDataLayout = new javax.swing.GroupLayout(pnData);
        pnData.setLayout(pnDataLayout);
        pnDataLayout.setHorizontalGroup(
            pnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDataLayout.createSequentialGroup()
                        .addGroup(pnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnDataLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1))
                            .addGroup(pnDataLayout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBatal)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                        .addGroup(pnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbxCari, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnDataLayout.createSequentialGroup()
                                .addComponent(dateCoser, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(pnDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnDataLayout.setVerticalGroup(
            pnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDataLayout.createSequentialGroup()
                        .addGroup(pnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateCoser, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxCari, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnBatal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHapus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTambah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnMain.add(pnData, "card2");

        pnTambah.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator3.setBackground(new java.awt.Color(79, 42, 24));
        jSeparator3.setForeground(new java.awt.Color(79, 42, 24));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(79, 42, 24));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/supply1.png"))); // NOI18N
        jLabel3.setText("Tambah Supply");

        btnBatal2.setBackground(new java.awt.Color(166, 145, 138));
        btnBatal2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBatal2.setForeground(new java.awt.Color(166, 145, 138));
        btnBatal2.setText("BATAL");
        btnBatal2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBatal2MouseMoved(evt);
            }
        });
        btnBatal2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBatal2MouseExited(evt);
            }
        });
        btnBatal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatal2ActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(79, 42, 24));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(79, 42, 24));
        btnSimpan.setText("SIMPAN");
        btnSimpan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSimpanMouseMoved(evt);
            }
        });
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSimpanMouseExited(evt);
            }
        });
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cafe2K.png"))); // NOI18N

        tfNo1.setEditable(false);
        tfNo1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfNo1.setForeground(new java.awt.Color(79, 42, 24));
        tfNo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNo1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(79, 42, 24));
        jLabel6.setText("NO :");

        jPanelCustom1.setBackground(new java.awt.Color(79, 42, 24));
        jPanelCustom1.setKananAtas(20);
        jPanelCustom1.setKananBawah(20);
        jPanelCustom1.setKiriAtas(20);
        jPanelCustom1.setKiriBawah(20);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tanggal");

        tfTgl.setEditable(false);
        tfTgl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfTgl.setForeground(new java.awt.Color(79, 42, 24));
        tfTgl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfTgl.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Total");

        tfTotal.setEditable(false);
        tfTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfTotal.setForeground(new java.awt.Color(79, 42, 24));
        tfTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));

        javax.swing.GroupLayout jPanelCustom1Layout = new javax.swing.GroupLayout(jPanelCustom1);
        jPanelCustom1.setLayout(jPanelCustom1Layout);
        jPanelCustom1Layout.setHorizontalGroup(
            jPanelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfTotal)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelCustom1Layout.setVerticalGroup(
            jPanelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCustom1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tfTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanelCustom2.setBackground(new java.awt.Color(79, 42, 24));
        jPanelCustom2.setKananAtas(20);
        jPanelCustom2.setKananBawah(20);
        jPanelCustom2.setKiriAtas(20);
        jPanelCustom2.setKiriBawah(20);

        jPanelCustom4.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCustom4.setKananAtas(20);
        jPanelCustom4.setKananBawah(20);
        jPanelCustom4.setKiriAtas(20);
        jPanelCustom4.setKiriBawah(20);

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(79, 42, 24));
        jLabel13.setText("ID Supplier");

        tfId.setEditable(false);
        tfId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfId.setForeground(new java.awt.Color(79, 42, 24));
        tfId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));

        jButton4.setBackground(new java.awt.Color(166, 145, 138));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Tambah Bahan");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tfNama.setEditable(false);
        tfNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfNama.setForeground(new java.awt.Color(79, 42, 24));
        tfNama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(79, 42, 24));
        jLabel15.setText("Nama");

        javax.swing.GroupLayout jPanelCustom4Layout = new javax.swing.GroupLayout(jPanelCustom4);
        jPanelCustom4.setLayout(jPanelCustom4Layout);
        jPanelCustom4Layout.setHorizontalGroup(
            jPanelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCustom4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom4Layout.createSequentialGroup()
                        .addComponent(tfId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanelCustom4Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelCustom4Layout.createSequentialGroup()
                        .addComponent(tfNama)
                        .addContainerGap())))
        );
        jPanelCustom4Layout.setVerticalGroup(
            jPanelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfId)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Supplier");

        javax.swing.GroupLayout jPanelCustom2Layout = new javax.swing.GroupLayout(jPanelCustom2);
        jPanelCustom2.setLayout(jPanelCustom2Layout);
        jPanelCustom2Layout.setHorizontalGroup(
            jPanelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCustom4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCustom2Layout.setVerticalGroup(
            jPanelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCustom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelCustom3.setBackground(new java.awt.Color(79, 42, 24));
        jPanelCustom3.setKananAtas(20);
        jPanelCustom3.setKananBawah(20);
        jPanelCustom3.setKiriAtas(20);
        jPanelCustom3.setKiriBawah(20);

        jPanelCustom5.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCustom5.setKananAtas(20);
        jPanelCustom5.setKananBawah(20);
        jPanelCustom5.setKiriAtas(20);
        jPanelCustom5.setKiriBawah(20);

        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(79, 42, 24));
        jLabel17.setText("Kode");

        tfKode.setEditable(false);
        tfKode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfKode.setForeground(new java.awt.Color(79, 42, 24));
        tfKode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfKode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));

        jButton5.setBackground(new java.awt.Color(166, 145, 138));
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Tambah Bahan");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tfNamaMenu.setEditable(false);
        tfNamaMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfNamaMenu.setForeground(new java.awt.Color(79, 42, 24));
        tfNamaMenu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNamaMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));

        jLabel19.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(79, 42, 24));
        jLabel19.setText("Nama");

        tfJml.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfJml.setForeground(new java.awt.Color(79, 42, 24));
        tfJml.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfJml.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));
        tfJml.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfJmlFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfJmlFocusLost(evt);
            }
        });
        tfJml.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfJmlKeyTyped(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(79, 42, 24));
        jLabel21.setText("Jumlah");

        tfSubtotal.setEditable(false);
        tfSubtotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfSubtotal.setForeground(new java.awt.Color(79, 42, 24));
        tfSubtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSubtotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));

        jLabel23.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(79, 42, 24));
        jLabel23.setText("Subtotal");

        jLabel24.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(79, 42, 24));
        jLabel24.setText("Harga");

        tfHarga.setEditable(false);
        tfHarga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfHarga.setForeground(new java.awt.Color(79, 42, 24));
        tfHarga.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfHarga.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));

        tfKet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfKet.setForeground(new java.awt.Color(79, 42, 24));
        tfKet.setText("Tidak Ada");
        tfKet.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));
        tfKet.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfKetFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfKetFocusLost(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(79, 42, 24));
        jLabel25.setText("Ketrangan");

        javax.swing.GroupLayout jPanelCustom5Layout = new javax.swing.GroupLayout(jPanelCustom5);
        jPanelCustom5.setLayout(jPanelCustom5Layout);
        jPanelCustom5Layout.setHorizontalGroup(
            jPanelCustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCustom5Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom5Layout.createSequentialGroup()
                        .addComponent(tfKode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom5Layout.createSequentialGroup()
                        .addComponent(tfNamaMenu)
                        .addContainerGap())
                    .addGroup(jPanelCustom5Layout.createSequentialGroup()
                        .addGroup(jPanelCustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfJml, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCustom5Layout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tfHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanelCustom5Layout.createSequentialGroup()
                        .addGroup(jPanelCustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelCustom5Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom5Layout.createSequentialGroup()
                        .addGroup(jPanelCustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfKet, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfSubtotal))
                        .addContainerGap())))
        );
        jPanelCustom5Layout.setVerticalGroup(
            jPanelCustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(4, 4, 4)
                .addGroup(jPanelCustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfKode)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNamaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfJml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfHarga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfKet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel26.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Bahan");

        btnTambah1.setBackground(new java.awt.Color(166, 145, 138));
        btnTambah1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah1.setForeground(new java.awt.Color(166, 145, 138));
        btnTambah1.setText("TAMBAH BAHAN");
        btnTambah1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnTambah1MouseMoved(evt);
            }
        });
        btnTambah1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTambah1MouseExited(evt);
            }
        });
        btnTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCustom3Layout = new javax.swing.GroupLayout(jPanelCustom3);
        jPanelCustom3.setLayout(jPanelCustom3Layout);
        jPanelCustom3Layout.setHorizontalGroup(
            jPanelCustom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCustom5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTambah1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCustom3Layout.setVerticalGroup(
            jPanelCustom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustom3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCustom5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTambah1)
                .addContainerGap())
        );

        tblMn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama", "Harga", "Jumlah", "Subtotal", "Keterangan"
            }
        ));
        tblMn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMnMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblMn);

        btnHapus1.setBackground(new java.awt.Color(200, 0, 0));
        btnHapus1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus1.setForeground(new java.awt.Color(200, 0, 0));
        btnHapus1.setText("HAPUS BAHAN");
        btnHapus1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnHapus1MouseMoved(evt);
            }
        });
        btnHapus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHapus1MouseExited(evt);
            }
        });
        btnHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapus1ActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(79, 42, 24));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(79, 42, 24));
        btnUbah.setText("UBAH BAHAN");
        btnUbah.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnUbahMouseMoved(evt);
            }
        });
        btnUbah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUbahMouseExited(evt);
            }
        });
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnBatal3.setBackground(new java.awt.Color(166, 145, 138));
        btnBatal3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBatal3.setForeground(new java.awt.Color(166, 145, 138));
        btnBatal3.setLabel("BATAL");
        btnBatal3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBatal3MouseMoved(evt);
            }
        });
        btnBatal3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBatal3MouseExited(evt);
            }
        });
        btnBatal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatal3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTambahLayout = new javax.swing.GroupLayout(pnTambah);
        pnTambah.setLayout(pnTambahLayout);
        pnTambahLayout.setHorizontalGroup(
            pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(pnTambahLayout.createSequentialGroup()
                .addGroup(pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTambahLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnTambahLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelCustom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelCustom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBatal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelCustom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnTambahLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(pnTambahLayout.createSequentialGroup()
                                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBatal3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        pnTambahLayout.setVerticalGroup(
            pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTambahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfNo1)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnTambahLayout.createSequentialGroup()
                        .addComponent(jPanelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal2))
                    .addGroup(pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTambahLayout.createSequentialGroup()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnUbah)
                                .addComponent(btnHapus1)
                                .addComponent(btnBatal3)))
                        .addComponent(jPanelCustom3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        pnMain.add(pnTambah, "card3");

        add(pnMain, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseExited
        btnTambah.setForeground(new Color(79, 42, 24));
        Icon tambah = new ImageIcon(getClass().getResource("/img/tambah1.png"));
        btnTambah.setIcon(tambah);
    }//GEN-LAST:event_btnTambahMouseExited

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        String sc = tfCari.getText();
        Date sc1 = dateCoser.getDate();
        List list = new ArrayList();
        switch (cbxCari.getSelectedIndex()) {
            case 0:
                list = servis.getByNO(sc);
                break;
            case 1:
                list = servis.getByTanggal(sc1);
                break;
            case 2:
                list = servis.getByPetugas(sc);
                break;
            case 3:
                list = servis.getBySupplier(sc);
                break;
        }
        tbl.setData(list);
    }//GEN-LAST:event_btnCariActionPerformed

    private void tfCariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCariFocusGained
        if (tfCari.getText().equals("Cari") || tfCari.getText().equalsIgnoreCase(""))
            tfCari.setText("");
    }//GEN-LAST:event_tfCariFocusGained

    private void tfCariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCariFocusLost
        if (tfCari.getText().equals("Cari") || tfCari.getText().equalsIgnoreCase(""))
            tfCari.setText("Cari");
    }//GEN-LAST:event_tfCariFocusLost

    private void btnTambahMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseMoved
        btnTambah.setForeground(Color.WHITE);
        Icon tambah = new ImageIcon(getClass().getResource("/img/tambah.png"));
        btnTambah.setIcon(tambah);
    }//GEN-LAST:event_btnTambahMouseMoved

    private void btnHapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseExited
        btnHapus.setForeground(new Color(200, 0, 0));
        btnHapus.setIcon(new ImageIcon(getClass().getResource("/img/hapus1.png")));
    }//GEN-LAST:event_btnHapusMouseExited

    private void btnBatalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseExited
        btnBatal.setForeground(new Color(0, 0, 200));
        btnBatal.setIcon(new ImageIcon(getClass().getResource("/img/batal1.png")));
    }//GEN-LAST:event_btnBatalMouseExited

    private void btnHapusMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseMoved
        btnHapus.setForeground(Color.WHITE);
        btnHapus.setIcon(new ImageIcon(getClass().getResource("/img/hapus.png")));
    }//GEN-LAST:event_btnHapusMouseMoved

    private void btnBatalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseMoved
        btnBatal.setForeground(Color.WHITE);
        btnBatal.setIcon(new ImageIcon(getClass().getResource("/img/batal.png")));
    }//GEN-LAST:event_btnBatalMouseMoved

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        resetData();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        MenuUtama.setAktif(false);
        pnMain.removeAll();
        pnMain.add(pnTambah);
        pnMain.repaint();
        pnMain.revalidate();

        Date now = new Date();
        SimpleDateFormat nonformat = new SimpleDateFormat("dd-MM-yyyy");
        Supplier mod = new DaoSupplier().getById("S000000001");
        tfNama.setText(mod.getNama());
        tfId.setText(mod.getIdSupplier());
        tfTgl.setText(nonformat.format(now));
        tfNo1.setText(servis.getNomer());
        resetTable();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        String s = (String) tblConten.getValueAt(tblConten.getSelectedRow(), 1);
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/hapus1.png"));
        if (JOptionPane.showConfirmDialog(null, "Menghapus pembelian dengan NO " + s, "Apakah anda yakin", 0, 0, icon) == 0) {
            servis.hapusData(s);
        }
        resetData();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblContenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContenMouseClicked
        btnBatal.setVisible(true);
        btnHapus.setVisible(true);
        pnDetail.setVisible(true);
        Supply mb = servis.getByNo(tblConten.getValueAt(tblConten.getSelectedRow(), 1).toString());
        tfNo.setText(mb.getSupplyPK().getNoSupply());
        lbTgl.setText(mb.getTgl());
        lbTotal.setText(Rupiah.getRp(mb.getTotal()));
        lbIdPel.setText(mb.getSupplier().getIdSupplier());
        lbNamaPel.setText(mb.getSupplier().getNama());
        lbIdPet.setText(mb.getPegawai().getIdPegawai());
        lbNamaPet.setText(mb.getPegawai().getNama());
        tblP.setData(mb);
    }//GEN-LAST:event_tblContenMouseClicked

    private void tblConten1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConten1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblConten1MouseClicked

    private void btnBatal1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatal1MouseMoved
        btnBatal1.setForeground(Color.WHITE);
        btnBatal1.setIcon(new ImageIcon(getClass().getResource("/img/report.png")));
    }//GEN-LAST:event_btnBatal1MouseMoved

    private void btnBatal1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatal1MouseExited
        btnBatal1.setForeground(new Color(0, 200, 0));
        btnBatal1.setIcon(new ImageIcon(getClass().getResource("/img/report1.png")));
    }//GEN-LAST:event_btnBatal1MouseExited

    private void btnBatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatal1ActionPerformed
        new DaoLaporan().cetakNotaSupply(servis.getByNo(tfNo.getText()));
    }//GEN-LAST:event_btnBatal1ActionPerformed

    private void btnBatal2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatal2MouseMoved
        btnBatal.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnBatal2MouseMoved

    private void btnBatal2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatal2MouseExited
        btnBatal.setForeground(new Color(166, 145, 138));
    }//GEN-LAST:event_btnBatal2MouseExited

    private void btnBatal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatal2ActionPerformed
        DefaultTableModel tbl1 = (DefaultTableModel) tblMn.getModel();
        resetTable();
        tfTotal.setText("");
        tbl1.setRowCount(0);
        back();
    }//GEN-LAST:event_btnBatal2ActionPerformed

    private void btnSimpanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseMoved
        btnSimpan.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnSimpanMouseMoved

    private void btnSimpanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseExited
        btnSimpan.setForeground(new Color(79, 42, 24));
    }//GEN-LAST:event_btnSimpanMouseExited

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (validPesanan()) {
            Supply mod = new Supply();
            SupplyPK pk = new SupplyPK();
            pk.setIdPegawai(MenuUtama.mod.getIdPegawai());
            pk.setIdSupplier(tfId.getText());
            pk.setNoSupply(tfNo1.getText());
            mod.setSupplyPK(pk);
            mod.setPegawai(MenuUtama.mod);
            mod.setSupplier(new DaoSupplier().getById(tfId.getText()));
            mod.setTgl(tfTgl.getText());
            mod.setTotal(Rupiah.getBigInt(tfTotal.getText()));
            List<DetailSupply> list = new ArrayList();
            DefaultTableModel tbl1 = (DefaultTableModel) tblMn.getModel();
            int index = tbl1.getRowCount() - 1;
            for (int i = 0; i <= index; i++) {
                DetailSupply p = new DetailSupply();
                DetailSupplyPK ds = new DetailSupplyPK();
                ds.setIdPegawai(MenuUtama.mod.getIdPegawai());
                ds.setIdSupplier(tfId.getText());
                ds.setNoSupply(tfNo1.getText());
                ds.setKodeBahan(tbl1.getValueAt(i, 0).toString());
                p.setJumlah(Integer.parseInt(tbl1.getValueAt(i, 3).toString()));
                p.setSubtotal(Rupiah.getBigInt(tbl1.getValueAt(i, 4).toString()));
                p.setDetailSupplyPK(ds);
                p.setBahan(new DaoBahan().getByKode(tbl1.getValueAt(i, 0).toString()));
                p.setSupply(mod);
                p.setKeterangan(tbl1.getValueAt(i, 5).toString());
                list.add(p);
            }
            mod.setDetailSupplyCollection(list);
            servis.tambahData(mod);
            String s = "Supply berhasil.\nApakah anda ingin mencetak nota ?";
            ImageIcon icon = new ImageIcon(getClass().getResource("/img/laporan1.png"));
            if (JOptionPane.showConfirmDialog(this, s, "Pemberitahuan", 0, 0, icon) == 0) {
                new DaoLaporan().cetakNotaSupply(mod);
            }
            resetTable();
            tfTotal.setText("");
            tbl1.setRowCount(0);
            back();
        }
        tfNo.setText(servis.getNomer());
        jLabel3.requestFocus();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        PilihSupplier pn = new PilihSupplier(null, true);
        pn.setVisible(true);
        try {
            tfId.setText(pn.mod.getIdSupplier());
            tfNama.setText(pn.mod.getNama());
        } catch (NullPointerException e) {
        }
        jLabel3.requestFocus();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        PilihBahan pn = new PilihBahan(null, true);
        pn.setVisible(true);
        try {
            tfKode.setText(pn.mod.getKodeBahan());
            tfNamaMenu.setText(pn.mod.getNama());
            tfHarga.setText(pn.mod.getRpHarga());
        } catch (NullPointerException e) {
        }
        jLabel3.requestFocus();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tfJmlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfJmlKeyTyped
        char a = evt.getKeyChar();
        if (!Character.isDigit(a)) {
            evt.consume();
        } else {
            String s = tfJml.getText() + String.copyValueOf(new char[]{a});
            long l = Rupiah.getLong(tfHarga.getText());
            tfSubtotal.setText(Rupiah.getRp(l * Long.parseLong(s)));
        }
    }//GEN-LAST:event_tfJmlKeyTyped

    private void tfKetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfKetFocusGained
        if (tfKet.getText().equals("Tidak Ada"))
            tfKet.setText("");
    }//GEN-LAST:event_tfKetFocusGained

    private void tfKetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfKetFocusLost
        if (tfKet.getText().equals(""))
            tfKet.setText("Tidak Ada");
    }//GEN-LAST:event_tfKetFocusLost

    private void btnTambah1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambah1MouseMoved
        btnTambah.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnTambah1MouseMoved

    private void btnTambah1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambah1MouseExited
        btnTambah.setForeground(new Color(166, 145, 138));
    }//GEN-LAST:event_btnTambah1MouseExited

    private void btnTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah1ActionPerformed
        if (validMenu()) {
            DefaultTableModel tbl1 = (DefaultTableModel) tblMn.getModel();
            String kode = tfKode.getText();
            String nama = tfNamaMenu.getText();
            int jml = Integer.parseInt(tfJml.getText());
            long harga = Rupiah.getLong(tfHarga.getText());
            long subtotal = jml * harga;
            String ket = tfKet.getText();
            int c = -1;
            for (int i = 0; i < tbl1.getRowCount(); i++) {
                if (tbl1.getValueAt(i, 0).toString().equals(kode)) {
                    c = i;
                }
            }
            if (c == -1) {
                tbl1.addRow(new Object[]{kode, nama, Rupiah.getRp(harga), jml, Rupiah.getRp(subtotal), ket});
            } else {
                int nJml = Integer.parseInt(tbl1.getValueAt(c, 3).toString()) + jml;
                long nSubtotal = Rupiah.getLong(tbl1.getValueAt(c, 4).toString()) + subtotal;
                if (btnTambah1.getText().equals("TAMBAH BAHAN")) {
                    tbl1.setValueAt(nJml, c, 3);
                    tbl1.setValueAt(Rupiah.getRp(nSubtotal), c, 4);
                } else {
                    tbl1.setValueAt(jml, c, 3);
                    tbl1.setValueAt(Rupiah.getRp(subtotal), c, 4);
                }
                tbl1.setValueAt(ket, c, 5);
            }
            tblMn.setModel(tbl1);
            resetTable();
            setTotal();
        }
        jLabel3.requestFocus();
    }//GEN-LAST:event_btnTambah1ActionPerformed

    private void tblMnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMnMouseClicked
        btnHapus1.setVisible(true);
        btnUbah.setVisible(true);
        btnBatal3.setVisible(true);
    }//GEN-LAST:event_tblMnMouseClicked

    private void btnHapus1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapus1MouseMoved
        btnHapus.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnHapus1MouseMoved

    private void btnHapus1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapus1MouseExited
        btnHapus.setForeground(new Color(200, 0, 0));
    }//GEN-LAST:event_btnHapus1MouseExited

    private void btnHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapus1ActionPerformed
        DefaultTableModel tbl1 = (DefaultTableModel) tblMn.getModel();
        int index = tblMn.getSelectedRow();
        tbl1.removeRow(index);
        tblMn.setModel(tbl1);
        jLabel1.requestFocus();
        resetTable();
    }//GEN-LAST:event_btnHapus1ActionPerformed

    private void btnUbahMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahMouseMoved
        btnUbah.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnUbahMouseMoved

    private void btnUbahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahMouseExited
        btnUbah.setForeground(new Color(79, 42, 24));
    }//GEN-LAST:event_btnUbahMouseExited

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        DefaultTableModel tbl1 = (DefaultTableModel) tblMn.getModel();
        tfKode.setText(tbl1.getValueAt(tblMn.getSelectedRow(), 0).toString());
        tfNamaMenu.setText(tbl1.getValueAt(tblMn.getSelectedRow(), 1).toString());
        tfHarga.setText(tbl1.getValueAt(tblMn.getSelectedRow(), 2).toString());
        tfJml.setText(tbl1.getValueAt(tblMn.getSelectedRow(), 3).toString());
        tfSubtotal.setText(tbl1.getValueAt(tblMn.getSelectedRow(), 4).toString());
        tfKet.setText(tbl1.getValueAt(tblMn.getSelectedRow(), 5).toString());
        btnTambah1.setText("PERBARUI BAHAN");
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnBatal3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatal3MouseMoved
        btnBatal1.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnBatal3MouseMoved

    private void btnBatal3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatal3MouseExited
        btnBatal1.setForeground(new Color(166, 145, 138));
    }//GEN-LAST:event_btnBatal3MouseExited

    private void btnBatal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatal3ActionPerformed
        resetTable();
    }//GEN-LAST:event_btnBatal3ActionPerformed

    private void tfJmlFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfJmlFocusGained
        if (tfJml.getText().equals("0"))
            tfJml.setText("");
    }//GEN-LAST:event_tfJmlFocusGained

    private void tfJmlFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfJmlFocusLost
        if (tfJml.getText().equals(""))
            tfJml.setText("0");
    }//GEN-LAST:event_tfJmlFocusLost

    private void cbxCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCariActionPerformed
        if (cbxCari.getSelectedIndex() == 1) {
            tfCari.setVisible(false);
            dateCoser.setVisible(true);
        } else {
            dateCoser.setVisible(false);
            tfCari.setVisible(true);
        }
        tfCari.setText("Cari");
    }//GEN-LAST:event_cbxCariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBatal1;
    private javax.swing.JButton btnBatal2;
    private javax.swing.JButton btnBatal3;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHapus1;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTambah1;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cbxCari;
    private com.toedter.calendar.JDateChooser dateCoser;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private custom.JPanelCustom jPanelCustom1;
    private custom.JPanelCustom jPanelCustom2;
    private custom.JPanelCustom jPanelCustom3;
    private custom.JPanelCustom jPanelCustom4;
    private custom.JPanelCustom jPanelCustom5;
    private custom.JPanelCustom jPanelCustom6;
    private custom.JPanelCustom jPanelCustom7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbIdPel;
    private javax.swing.JLabel lbIdPet;
    private javax.swing.JLabel lbNamaPel;
    private javax.swing.JLabel lbNamaPet;
    private javax.swing.JLabel lbTgl;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JPanel pnData;
    private javax.swing.JPanel pnDetail;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnTambah;
    private javax.swing.JTable tblConten;
    private javax.swing.JTable tblConten1;
    private javax.swing.JTable tblMn;
    private javax.swing.JTextField tfCari;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfJml;
    private javax.swing.JTextField tfKet;
    private javax.swing.JTextField tfKode;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNamaMenu;
    private javax.swing.JTextField tfNo;
    private javax.swing.JTextField tfNo1;
    private javax.swing.JTextField tfSubtotal;
    private javax.swing.JTextField tfTgl;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables

    private void resetData() {
        tblConten.setModel(tbl);
        tblConten1.setModel(tblP);
        int[] tbC = {0, 1, 2};
        int[] tbCW = {35, 90, 70};
        int[] tbC1 = {0, 1, 5};
        int[] tbC1W = {35, 70, 70};
        setColWidht(tblConten, tbC, tbCW);
        setColWidht(tblConten1, tbC1, tbC1W);
        tbl.setData(servis.ambilData());
        btnBatal.setVisible(false);
        btnHapus.setVisible(false);
        pnDetail.setVisible(false);
        btnTambah.setVisible(true);
        dateCoser.setVisible(false);
        btnTambah.setForeground(new Color(79, 42, 24));
        Icon tambah = new ImageIcon(getClass().getResource("/img/tambah1.png"));
        btnTambah.setIcon(tambah);
        jLabel1.requestFocus();
    }

    private void setColWidht(JTable tb, int[] noCol, int[] noColW) {
        TableColumnModel tblModel = tb.getColumnModel();
        for (int i = 0; i < noCol.length; i++) {
            tblModel.getColumn(noCol[i]).setPreferredWidth(noColW[i]);
            tblModel.getColumn(noCol[i]).setMaxWidth(noColW[i]);
            tblModel.getColumn(noCol[i]).setMinWidth(noColW[i]);
        }
    }

    private void back() {
        MenuUtama.setAktif(true);
        pnMain.removeAll();
        pnMain.add(pnData);
        pnMain.repaint();
        pnMain.revalidate();
        resetData();
    }

    void resetTable() {
        btnHapus1.setVisible(false);
        btnUbah.setVisible(false);
        btnBatal3.setVisible(false);
        tblMn.clearSelection();

        tfKode.setText("");
        tfNamaMenu.setText("");
        tfJml.setText("");
        tfHarga.setText("0");
        tfSubtotal.setText("0");
        tfKet.setText("Tidak Ada");
        btnTambah1.setText("TAMBAH BAHAN");
    }

    private void setTotal() {
        DefaultTableModel tbll = (DefaultTableModel) tblMn.getModel();
        long i = 0;
        for (int a = 0; a < tbll.getRowCount(); a++) {
            i = i + Rupiah.getLong(tbll.getValueAt(a, 4).toString());
        }
        tfTotal.setText(Rupiah.getRp(i));
    }

    private boolean validMenu() {
        boolean valid = true;
        if (tfKode.getText().equals("")) {
            valid = false;
            JOptionPane.showMessageDialog(this, "Pilih Bahn terlebih dahulu");
        } else if (tfJml.getText().equals("") || tfJml.getText().equals("0")) {
            valid = false;
            JOptionPane.showMessageDialog(this, "Masukkan jumlah bahan terlebih dahulu");
        }
        return valid;
    }

    private boolean validPesanan() {
        boolean valid = true;
        if (tfId.getText().equals("")) {
            valid = false;
            JOptionPane.showMessageDialog(this, "Pilih Supplier terlebih dahulu");
        } else if (tblMn.getRowCount() == 0) {
            valid = false;
            JOptionPane.showMessageDialog(this, "Pilih Bahan terlebih dahulu");
        }
        return valid;
    }

}
