/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.DaoLaporan;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author fatiq
 */
public class MenuLaporan extends javax.swing.JPanel {

    /**
     * Creates new form MenuPetugas
     */
    public MenuLaporan() {
        initComponents();
        pnTgl.setVisible(false);
        btnLoad.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinField1 = new com.toedter.components.JSpinField();
        pnMain = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cbxPilih = new javax.swing.JComboBox<>();
        pnTgl = new javax.swing.JPanel();
        bulan = new javax.swing.JComboBox<>();
        tahun = new javax.swing.JSpinner();
        btnLoad = new javax.swing.JButton();
        pnLaporan = new javax.swing.JPanel();

        setLayout(new java.awt.CardLayout());

        pnMain.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator1.setBackground(new java.awt.Color(79, 42, 24));
        jSeparator1.setForeground(new java.awt.Color(79, 42, 24));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(79, 42, 24));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/laporan1.png"))); // NOI18N
        jLabel1.setText("Laporan Cafe2K");

        jPanel1.setBackground(new java.awt.Color(79, 42, 24));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 42, 24)));

        cbxPilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Laporan-", "Pembelian per Bulan", "Supply per Bulan", "Masak per Bulan" }));
        cbxPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPilihActionPerformed(evt);
            }
        });

        pnTgl.setBackground(new java.awt.Color(255, 255, 255));

        bulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        tahun.setModel(new javax.swing.SpinnerNumberModel(1000, 1000, 9999, 1));
        tahun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tahunKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnTglLayout = new javax.swing.GroupLayout(pnTgl);
        pnTgl.setLayout(pnTglLayout);
        pnTglLayout.setHorizontalGroup(
            pnTglLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTglLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTglLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bulan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tahun))
                .addContainerGap())
        );
        pnTglLayout.setVerticalGroup(
            pnTglLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTglLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLoad.setBackground(new java.awt.Color(166, 145, 138));
        btnLoad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLoad.setForeground(new java.awt.Color(166, 145, 138));
        btnLoad.setText("LOAD");
        btnLoad.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnLoadMouseMoved(evt);
            }
        });
        btnLoad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoadMouseExited(evt);
            }
        });
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxPilih, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnTgl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLoad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxPilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLoad)
                .addContainerGap(324, Short.MAX_VALUE))
        );

        pnLaporan.setBackground(new java.awt.Color(255, 255, 255));
        pnLaporan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 42, 24)));

        javax.swing.GroupLayout pnLaporanLayout = new javax.swing.GroupLayout(pnLaporan);
        pnLaporan.setLayout(pnLaporanLayout);
        pnLaporanLayout.setHorizontalGroup(
            pnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        pnLaporanLayout.setVerticalGroup(
            pnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMainLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnMainLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(pnMain, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
        int bln = bulan.getSelectedIndex();
        int th = Integer.parseInt(tahun.getValue().toString());
        switch (cbxPilih.getSelectedIndex()) {
            case 1:
                new DaoLaporan().cetakPembelianPerBulan(pnLaporan, bln, th);
                break;
            case 2:
                new DaoLaporan().cetakSupplyPerBulan(pnLaporan, bln, th);
                break;
            case 3:
                new DaoLaporan().cetakMasakPerBulan(pnLaporan, bln, th);
                break;
        }
    }//GEN-LAST:event_btnLoadActionPerformed

    private void cbxPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPilihActionPerformed
        if (cbxPilih.getSelectedIndex() != 0) {
            Date d = new Date();
            SimpleDateFormat dt = new SimpleDateFormat("MM-yyyy");
            String[] s = dt.format(d).split("-");
            bulan.setSelectedIndex(Integer.parseInt(s[0]) - 1);
            tahun.setValue(Integer.parseInt(s[1]));
            pnTgl.setVisible(true);
            btnLoad.setVisible(true);
        } else {
            pnTgl.setVisible(false);
            btnLoad.setVisible(false);
            pnLaporan.removeAll();
        }
    }//GEN-LAST:event_cbxPilihActionPerformed

    private void tahunKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tahunKeyTyped
        char a = evt.getKeyChar();
        if ((!Character.isDigit(a)) || tahun.getValue().toString().length() >= 4)
            evt.consume();
    }//GEN-LAST:event_tahunKeyTyped

    private void btnLoadMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadMouseMoved
        btnLoad.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnLoadMouseMoved

    private void btnLoadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoadMouseExited
        btnLoad.setForeground(new Color(166, 145, 138));
    }//GEN-LAST:event_btnLoadMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoad;
    private javax.swing.JComboBox<String> bulan;
    private javax.swing.JComboBox<String> cbxPilih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.components.JSpinField jSpinField1;
    private javax.swing.JPanel pnLaporan;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnTgl;
    private javax.swing.JSpinner tahun;
    // End of variables declaration//GEN-END:variables

}
