/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import dao.DaoMasak;
import dao.DaoMenu;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DetailMasak;
import model.DetailMasakPK;
import model.Memasak;
import model.MemasakPK;
import model.Menu;
import servis.ServisMasak;

/**
 *
 * @author fatiq
 */
public class TambahMasakan extends javax.swing.JDialog {

    /**
     * Creates new form TambahPelanggan
     */
    int xx, xy;
    private ServisMasak servis = new DaoMasak();
    private Memasak mod = new Memasak();
    private Menu modM = new Menu();

    public TambahMasakan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Date now = new Date();
        SimpleDateFormat nonformat = new SimpleDateFormat("dd-MM-yyyy");
        tfTgl.setText(nonformat.format(now));
        tfId.setText(servis.getNomer());
        reset();
        jLabel1.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnSimpan = new custom.JPanelCustom();
        jLabel2 = new javax.swing.JLabel();
        btnBatal = new custom.JPanelCustom();
        jLabel7 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfTgl = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfKeterangan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfKode = new javax.swing.JTextField();
        lbKode = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        lbMenu = new javax.swing.JLabel();
        lbJml = new javax.swing.JLabel();
        tfJml = new javax.swing.JTextField();
        tfKom = new javax.swing.JTextField();
        lbKom = new javax.swing.JLabel();
        btnPilih = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal1 = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnBatal2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(79, 42, 24));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnSimpan.setBackground(new java.awt.Color(0, 200, 0));
        btnSimpan.setKananAtas(20);
        btnSimpan.setKananBawah(20);
        btnSimpan.setKiriAtas(20);
        btnSimpan.setKiriBawah(20);
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });
        btnSimpan.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SIMPAN");
        btnSimpan.add(jLabel2, "card2");

        btnBatal.setBackground(new java.awt.Color(200, 0, 0));
        btnBatal.setKananAtas(20);
        btnBatal.setKananBawah(20);
        btnBatal.setKiriAtas(20);
        btnBatal.setKiriBawah(20);
        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
        });
        btnBatal.setLayout(new java.awt.CardLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("BATAL");
        btnBatal.add(jLabel7, "card2");

        tfId.setEditable(false);
        tfId.setForeground(new java.awt.Color(79, 42, 24));
        tfId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(79, 42, 24));
        jLabel4.setText("No Masakan");

        tfTgl.setEditable(false);
        tfTgl.setForeground(new java.awt.Color(79, 42, 24));
        tfTgl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfTgl.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(79, 42, 24));
        jLabel5.setText("Tanggal");

        tfKeterangan.setForeground(new java.awt.Color(79, 42, 24));
        tfKeterangan.setText("Tidak Ada");
        tfKeterangan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));
        tfKeterangan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfKeteranganFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfKeteranganFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(79, 42, 24));
        jLabel9.setText("Keterangan");

        tfKode.setEditable(false);
        tfKode.setForeground(new java.awt.Color(79, 42, 24));
        tfKode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfKode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));

        lbKode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbKode.setForeground(new java.awt.Color(79, 42, 24));
        lbKode.setText("Kode Menu");

        tfNama.setEditable(false);
        tfNama.setForeground(new java.awt.Color(79, 42, 24));
        tfNama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));

        lbMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMenu.setForeground(new java.awt.Color(79, 42, 24));
        lbMenu.setText("Nama Menu");

        lbJml.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbJml.setForeground(new java.awt.Color(79, 42, 24));
        lbJml.setText("Jumlah");

        tfJml.setForeground(new java.awt.Color(79, 42, 24));
        tfJml.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfJml.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));
        tfJml.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfJmlKeyTyped(evt);
            }
        });

        tfKom.setEditable(false);
        tfKom.setForeground(new java.awt.Color(79, 42, 24));
        tfKom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(79, 42, 24)));

        lbKom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbKom.setForeground(new java.awt.Color(79, 42, 24));
        lbKom.setText("Komposisi");

        btnPilih.setBackground(new java.awt.Color(166, 145, 138));
        btnPilih.setForeground(new java.awt.Color(0, 0, 0));
        btnPilih.setText(".......");
        btnPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihActionPerformed(evt);
            }
        });

        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Menu", "Komposisi", "Jumlah"
            }
        ));
        tblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMenu);

        btnUbah.setBackground(new java.awt.Color(79, 42, 24));
        btnUbah.setForeground(new java.awt.Color(79, 42, 24));
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(200, 0, 0));
        btnHapus.setForeground(new java.awt.Color(200, 0, 0));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBatal1.setBackground(new java.awt.Color(166, 145, 138));
        btnBatal1.setForeground(new java.awt.Color(166, 145, 138));
        btnBatal1.setText("Batal");
        btnBatal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatal1ActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(79, 42, 24));
        btnTambah.setForeground(new java.awt.Color(79, 42, 24));
        btnTambah.setText("Tambah Menu");
        btnTambah.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnTambahMouseMoved(evt);
            }
        });
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTambahMouseExited(evt);
            }
        });
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnBatal2.setBackground(new java.awt.Color(166, 145, 138));
        btnBatal2.setForeground(new java.awt.Color(166, 145, 138));
        btnBatal2.setText("Batal");
        btnBatal2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBatal2MouseMoved(evt);
            }
        });
        btnBatal2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBatal2MouseExited(evt);
            }
        });
        btnBatal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatal2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnBatal2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbJml)
                                    .addComponent(tfJml, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbKom)
                                    .addComponent(tfKom)))
                            .addComponent(tfKeterangan)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(tfTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel9))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbKode)
                                    .addComponent(tfKode, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbMenu)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPilih, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTgl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfKeterangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbKode)
                                    .addComponent(lbMenu))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfKode)
                                    .addComponent(tfNama)))
                            .addComponent(btnPilih, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbJml)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfJml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbKom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfKom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBatal2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tambah Masakan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, "card3");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseClicked
        dispose();
    }//GEN-LAST:event_btnBatalMouseClicked

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        if (validData()) {
            DefaultTableModel tbl = (DefaultTableModel) tblMenu.getModel();
            MemasakPK pk = new MemasakPK();
            pk.setNoMasak(tfId.getText());
            pk.setIdPegawai(MenuUtama.mod.getIdPegawai());
            mod.setMemasakPK(pk);
            mod.setTgl(tfTgl.getText());
            mod.setKeterangan(tfKeterangan.getText());
            mod.setPegawai(MenuUtama.mod);
            List list = new ArrayList();
            for (int i = 0; i < tbl.getRowCount(); i++) {
                DetailMasak dm = new DetailMasak();
                DetailMasakPK dpk = new DetailMasakPK();
                Menu m = new DaoMenu().getByKode(tbl.getValueAt(i, 0).toString());
                dpk.setIdPegawai(MenuUtama.mod.getIdPegawai());
                dpk.setKodeMenu(m.getKodeMenu());
                dpk.setNoMasak(mod.getMemasakPK().getNoMasak());
                dm.setDetailMasakPK(dpk);
                dm.setMenu(m);
                dm.setMemasak(mod);
                dm.setJumlah(Integer.parseInt(tbl.getValueAt(i, 3).toString()));
                list.add(dm);
            }
            mod.setDetailMasakCollection(list);
            servis.tambahData(mod);
            dispose();
        }
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void tfKeteranganFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfKeteranganFocusGained
        if (tfKeterangan.getText().equals("Tidak Ada"))
            tfKeterangan.setText("");
    }//GEN-LAST:event_tfKeteranganFocusGained

    private void tfKeteranganFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfKeteranganFocusLost
        if (tfKeterangan.getText().equals("Tidak Ada"))
            tfKeterangan.setText("");
    }//GEN-LAST:event_tfKeteranganFocusLost

    private void btnPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihActionPerformed
        PilihMenu pn = new PilihMenu(null, true);
        pn.setVisible(true);
        try {
            this.modM = pn.mod;
            tfKode.setText(modM.getKodeMenu());
            tfNama.setText(modM.getNama());
            tfKom.setText(modM.getAllBahan());
        } catch (NullPointerException e) {
        }
        jLabel1.requestFocus();
    }//GEN-LAST:event_btnPilihActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        btnTambah.setText("Perbarui Menu");
        btnBatal2.setVisible(true);
        btnPilih.setVisible(true);

        tfKode.setVisible(true);
        tfNama.setVisible(true);
        tfJml.setVisible(true);
        tfKom.setVisible(true);

        lbKode.setVisible(true);
        lbMenu.setVisible(true);
        lbJml.setVisible(true);
        lbKom.setVisible(true);

        DefaultTableModel tbl = (DefaultTableModel) tblMenu.getModel();
        modM = new DaoMenu().getByKode(tbl.getValueAt(tblMenu.getSelectedRow(), 0).toString());
        tfKode.setText(tbl.getValueAt(tblMenu.getSelectedRow(), 0).toString());
        tfNama.setText(tbl.getValueAt(tblMenu.getSelectedRow(), 1).toString());
        tfJml.setText(tbl.getValueAt(tblMenu.getSelectedRow(), 3).toString());
        tfKom.setText(tbl.getValueAt(tblMenu.getSelectedRow(), 2).toString());
        jLabel1.requestFocus();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        DefaultTableModel tbl = (DefaultTableModel) tblMenu.getModel();
        tbl.removeRow(tblMenu.getSelectedRow());
        jLabel1.requestFocus();
        reset();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatal1ActionPerformed
        reset();
    }//GEN-LAST:event_btnBatal1ActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        DefaultTableModel tbl = (DefaultTableModel) tblMenu.getModel();
        if (!lbKode.isVisible()) {
            btnTambah.setText("Tambah Menu");
            btnBatal2.setVisible(true);
            btnPilih.setVisible(true);

            tfKode.setVisible(true);
            tfNama.setVisible(true);
            tfJml.setVisible(true);
            tfKom.setVisible(true);

            lbKode.setVisible(true);
            lbMenu.setVisible(true);
            lbJml.setVisible(true);
            lbKom.setVisible(true);
        } else {
            int jml = Integer.parseInt(tfJml.getText());
            int c = -1;
            for (int i = 0; i < tbl.getRowCount(); i++) {
                if (tbl.getValueAt(i, 0).toString().equals(tfKode.getText())) {
                    c = i;
                    modM = new DaoMenu().getByKode(tfKode.getText());
                }
            }
            if (c == -1) {
                if (modM.isBahanCukup(jml)) {
                    tbl.addRow(new Object[]{tfKode.getText(), tfNama.getText(), modM.getAllBahan(Integer.parseInt(tfJml.getText())), tfJml.getText()});
                    reset();
                } else {
                    JOptionPane.showMessageDialog(this, "Bahan tidak cukup");
                }
            } else {
                int k = Integer.parseInt(tbl.getValueAt(c, 3).toString());
                int j = jml + k;
                if (btnTambah.getText().equals("Tambah Menu")) {
                    if (modM.isBahanCukup(jml)) {
                        tbl.setValueAt(j, c, 3);
                        tbl.setValueAt(modM.getAllBahan(j), c, 2);
                        reset();
                    } else {
                        JOptionPane.showMessageDialog(this, "Bahan tidak cukup");
                    }
                } else {
                    if (modM.isBahanCukup(jml)) {
                        tbl.setValueAt(tfJml.getText(), c, 3);
                        tbl.setValueAt(modM.getAllBahan(jml), c, 2);
                        reset();
                    } else {
                        JOptionPane.showMessageDialog(this, "Bahan tidak cukup");
                    }
                }
            }
        }
        jLabel1.requestFocus();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnBatal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatal2ActionPerformed
        reset();
    }//GEN-LAST:event_btnBatal2ActionPerformed

    private void tfJmlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfJmlKeyTyped
        char a = evt.getKeyChar();
        if (!Character.isDigit(a)) {
            evt.consume();
        } else {
            String s = tfJml.getText() + String.copyValueOf(new char[]{a});
            tfKom.setText(modM.getAllBahan(Integer.parseInt(s)));
        }
    }//GEN-LAST:event_tfJmlKeyTyped

    private void btnTambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseExited
        btnTambah.setForeground(new Color(79, 42, 24));
    }//GEN-LAST:event_btnTambahMouseExited

    private void btnTambahMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseMoved
        btnTambah.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnTambahMouseMoved

    private void btnBatal2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatal2MouseMoved
        btnBatal2.setForeground(new Color(79, 42, 24));
    }//GEN-LAST:event_btnBatal2MouseMoved

    private void btnBatal2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatal2MouseExited
        btnBatal2.setForeground(new Color(166, 145, 138));
    }//GEN-LAST:event_btnBatal2MouseExited

    private void tblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMenuMouseClicked
        btnUbah.setVisible(true);
        btnHapus.setVisible(true);
        btnBatal1.setVisible(true);
    }//GEN-LAST:event_tblMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahMasakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahMasakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahMasakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahMasakan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TambahMasakan dialog = new TambahMasakan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private custom.JPanelCustom btnBatal;
    private javax.swing.JButton btnBatal1;
    private javax.swing.JButton btnBatal2;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnPilih;
    private custom.JPanelCustom btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbJml;
    private javax.swing.JLabel lbKode;
    private javax.swing.JLabel lbKom;
    private javax.swing.JLabel lbMenu;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfJml;
    private javax.swing.JTextField tfKeterangan;
    private javax.swing.JTextField tfKode;
    private javax.swing.JTextField tfKom;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfTgl;
    // End of variables declaration//GEN-END:variables

    private boolean validData() {
        boolean valid = true;
        if (tblMenu.getRowCount() == 0) {
            valid = false;
            JOptionPane.showMessageDialog(this, "Masukkan menu terlebih dahulu");
        }
        return valid;
    }

    private void reset() {
        tfKode.setText("");
        tfNama.setText("");
        tfJml.setText("");
        tfKom.setText("");

        btnBatal1.setVisible(false);
        btnBatal2.setVisible(false);
        btnUbah.setVisible(false);
        btnHapus.setVisible(false);
        btnPilih.setVisible(false);

        tfKode.setVisible(false);
        tfNama.setVisible(false);
        tfJml.setVisible(false);
        tfKom.setVisible(false);

        lbKode.setVisible(false);
        lbMenu.setVisible(false);
        lbJml.setVisible(false);
        lbKom.setVisible(false);

        tblMenu.requestFocus();
        btnTambah.setText("Tambah Menu");
        tblMenu.clearSelection();
    }
}
